### ISSUE TITLE
Key Error: Size when executing hatchet

### ISSUE THREAD

**Issue by AndrewWebster10** [raphael-group/hatchet#105]
Hi there,

I was attempting to run hatchet for the first time, and I am getting a KeyError error upon execution of the script.

python -m hatchet run hatchet.ini
Traceback (most recent call last):
  File "/home/andrew/anaconda3/envs/hatchet/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/andrew/anaconda3/envs/hatchet/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/andrew/anaconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/__main__.py", line 71, in <module>
    sys.exit(main())
  File "/home/andrew/anaconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/__main__.py", line 65, in main
    globals()[command](args)
  File "/home/andrew/anaconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/utils/run.py", line 50, in main
    '-b', config.count_reads.size,
  File "/home/andrew/anaconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/utils/config.py", line 50, in __getattr__
    return env_var or self.d[item]
KeyError: 'size'

My hatchet.ini file is below:

[run]
genotype_snps=True
count_alleles=True
count_reads=True
combine_counts=True
cluster_bins=True
plot_bins=True
compute_cn=True
plot_cn=True
reference=/mnt/d/hg38v2.fa
output=/mnt/d/output
processes=62
normal=/mnt/d/normal_f.sorted.markdup.bam
bams=/mnt/d/PDX_f.sorted.markdup.bam
samples=TumorSample1
[genotype_snps]
mincov=8
maxcov=300
reference_version=hg38
chr_notation=True
[count_alleles]
mincov=8
maxcov=300
[combine_counts]
msr=3000
mtr=5000

**Comment by vineetbansal** [comment]
Hello @AndrewWebster10 - the `size` key in `count_reads` is required if the `count_reads` step is enabled. We don't set a default value for this in the code but leave this to the user. You may want to start with the sample `hatchet.ini` provided at https://github.com/raphael-group/hatchet/blob/master/script/hatchet.ini, or copy-paste the `count_reads` section from there, modifying it as necessary.

@simozacca  - This `size` key is not included in the `hatchet.ini` that we ship with `HATCHet`, so there's no default value for this. I think this may have been a remnant of how things worked in the example bash script before we could run against an `.ini` file. Does it make sense to default it to `50kb`, or error out like we're doing here?

**Comment by AndrewWebster10** [comment]
@vineetbansal  Thanks so much. I got it to successfully run on a pair of tumor samples. 

On a second attempt with a different tumor pair however, I've run into a very perplexing error.... Any ideas?

[2021-Sep-30 19:29:37]# Counting number of identified SNPs
Traceback (most recent call last):
  File "/home/andrew/anaconda3/envs/hatchet/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/andrew/anaconda3/envs/hatchet/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/andrew/anaconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/__main__.py", line 71, in <module>
    sys.exit(main())
  File "/home/andrew/anaconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/__main__.py", line 65, in main
    globals()[command](args)
  File "/home/andrew/anaconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/utils/run.py", line 79, in main
    genotype_snps(
  File "/home/andrew/anaconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/utils/genotype_snps.py", line 40, in main
    raise ValueError(sp.error("No SNPs found in the normal!\n"))
**ValueError: No SNPs found in the normal!**

**Comment by simozacca** [comment]
This error is typically occurring when a reference genome different from the same exact reference genome used for generating the BAM files is provided. Since the original issue has been resolved, I will close this issue. However, please feel free to re-open it or to open new issues for additional problems.
