### ISSUE TITLE
Color Palette Issue

### ISSUE THREAD

**Issue by mkinnaman** [raphael-group/hatchet#11]
Hi SImone,

I pulled the most recent release and am running some additional sample but running into an issue with seaborn/matplotlib now.

I keep on getting this error throw:

`Traceback (most recent call last):
  File "/home/kinnamam/miniconda3/envs/hatch/hatchet/utils/BBot.py", line 464, in <module>
    main()
  File "/home/kinnamam/miniconda3/envs/hatch/hatchet/utils/BBot.py", line 74, in main
    clubb(bbc, clusters, args, out)
  File "/home/kinnamam/miniconda3/envs/hatch/hatchet/utils/BBot.py", line 257, in clubb
    g = sns.lmplot(data=df, x=lx, y=ly, hue=lh, hue_order=order, palette=args['cmap'], fit_reg=False, size=figsize[0], aspect=figsize[1], scatter_kws={"s":s}, legend=False, col=g, col_wrap=args['colwrap'])
  File "/home/kinnamam/.local/lib/python2.7/site-packages/seaborn/regression.py", line 588, in lmplot
    legend_out=legend_out)
  File "/home/kinnamam/.local/lib/python2.7/site-packages/seaborn/axisgrid.py", line 253, in __init__
    colors = self._get_palette(data, hue, hue_order, palette)
  File "/home/kinnamam/.local/lib/python2.7/site-packages/seaborn/axisgrid.py", line 174, in _get_palette
    colors = color_palette(palette, n_colors)
  File "/home/kinnamam/.local/lib/python2.7/site-packages/seaborn/palettes.py", line 235, in color_palette
    raise ValueError("%s is not a valid palette name" % palette)
ValueError: tab20 is not a valid palette name`

Might be a seaborn/matplotlib version issue. Prior to pulling latest code didn't have this issue.
Thanks,
MIchael

**Comment by simozacca** [comment]
Thank you for the interest in HATCHet!

It seems that the underlying version of matplotlib does not support `tab20`, however the HATCHet plotting component `BBot` supports different colormaps that you can specify through the flag `-m` or `--colormap`. For example, could you please try to run your plotting by specifying the colormap `-m Set2`?
```
${BBOT} [...] -m Set2
```
Could you please confirm whether the plotting is successfully working when using some other colormap?

Please see the list of all the supported colormaps at:
https://github.com/raphael-group/hatchet/blob/5cf33566948f269c85e1952002a3901cca3cf76a/utils/ArgParsing.py#L381

Also, you could use [colorbrewer](https://colorbrewer2.org/#type=qualitative&scheme=Accent&n=3) to decide the best qualitative colormap for your needs.

**Comment by simozacca** [comment]
We expect the issue to be solved. Please feel free to re-open the issue otherwise.
