### ISSUE TITLE
KeyError in count_alleles

### ISSUE THREAD

**Issue by wir963** [raphael-group/hatchet#113]
Hey, 

I'm using hatchet 4.9.0 (installed via bioconda) and I'm getting a strange error on the `count_alleles` step for one of my patients (I was able to run this for another patient so I don't think the error is on my end). I've also run through the demo end-to-end successfully. Here is the traceback information

```
Traceback (most recent call last):
  File "/gpfs/gsfs9/users/Robinson-SB/SB-workflows/CN-analysis/.snakemake/conda/c11c9886ddd3e3591e5ea64c07573fac/bin/hatchet", line 33, in <module>
    sys.exit(load_entry_point('hatchet==0.4.9', 'console_scripts', 'hatchet')())
  File "/gpfs/gsfs9/users/Robinson-SB/SB-workflows/CN-analysis/.snakemake/conda/c11c9886ddd3e3591e5ea64c07573fac/lib/python3.9/site-packages/hatchet/__main__.py", line 61, in main
    globals()[command](args)
  File "/gpfs/gsfs9/users/Robinson-SB/SB-workflows/CN-analysis/.snakemake/conda/c11c9886ddd3e3591e5ea64c07573fac/lib/python3.9/site-packages/hatchet/utils/count_alleles.py", line 60, in main
    counts = {c : {o : form(het(c[1])[o][0][0], het(c[1])[o][1][0], rcounts[c][o]) for o in rcounts[c]} for c in rcounts}
  File "/gpfs/gsfs9/users/Robinson-SB/SB-workflows/CN-analysis/.snakemake/conda/c11c9886ddd3e3591e5ea64c07573fac/lib/python3.9/site-packages/hatchet/utils/count_alleles.py", line 60, in <dictcomp>
    counts = {c : {o : form(het(c[1])[o][0][0], het(c[1])[o][1][0], rcounts[c][o]) for o in rcounts[c]} for c in rcounts}
  File "/gpfs/gsfs9/users/Robinson-SB/SB-workflows/CN-analysis/.snakemake/conda/c11c9886ddd3e3591e5ea64c07573fac/lib/python3.9/site-packages/hatchet/utils/count_alleles.py", line 60, in <dictcomp>
    counts = {c : {o : form(het(c[1])[o][0][0], het(c[1])[o][1][0], rcounts[c][o]) for o in rcounts[c]} for c in rcounts}
KeyError: 338906
```

Please let me know if you have any questions - I'm happy to help debug on my end as well. 

Best, Welles

**Comment by brian-arnold** [comment]
Hi Welles,

We are familiar with this particular KeyError and will hopefully have a fix within the next couple of days! 

However, if you do not want to wait, you can do the following. In the .ini file you use for each patient, under the section [count_alleles], specify the 'outputsnps' variable to point to the same directory as that specified for the output of the hatchet run (which should be patient-specific, a unique path for each hatchet run). For instance:

[run]
output = "directory/for/patient123"
[count_alleles]
outputsnps = "directory/for/patient123"

In any case, this will be fixed soon.

Sincerely,
Brian

**Comment by wir963** [comment]
Hey Brian, 

Okay thanks for the fix. After making that change, I'm no longer getting the error. I'll leave this issue open and you can close it when you merge in #111?

Out of curiosity, are you (the larger Raphael Group) planning to merge in #108 any time soon? I noticed that there are quite a few breaking changes and don't want to run too many samples through before this merge. 

Best, Welles

**Comment by wir963** [comment]
Hey @brian-arnold, 

Your suggested fix worked for some samples but I am still getting a similar issue when running over samples through when using the same input and output directory. See below.

```
Traceback (most recent call last):
  File "/gpfs/gsfs9/users/Robinson-SB/SB-workflows/CN-analysis/.snakemake/conda/c11c9886ddd3e3591e5ea64c07573fac/bin/hatchet", line 33, in <module>
    sys.exit(load_entry_point('hatchet==0.4.9', 'console_scripts', 'hatchet')())
  File "/gpfs/gsfs9/users/Robinson-SB/SB-workflows/CN-analysis/.snakemake/conda/c11c9886ddd3e3591e5ea64c07573fac/lib/python3.9/site-packages/hatchet/__main__.py", line 61, in main
    globals()[command](args)
  File "/gpfs/gsfs9/users/Robinson-SB/SB-workflows/CN-analysis/.snakemake/conda/c11c9886ddd3e3591e5ea64c07573fac/lib/python3.9/site-packages/hatchet/utils/count_alleles.py", line 60, in main
    counts = {c : {o : form(het(c[1])[o][0][0], het(c[1])[o][1][0], rcounts[c][o]) for o in rcounts[c]} for c in rcounts}
  File "/gpfs/gsfs9/users/Robinson-SB/SB-workflows/CN-analysis/.snakemake/conda/c11c9886ddd3e3591e5ea64c07573fac/lib/python3.9/site-packages/hatchet/utils/count_alleles.py", line 60, in <dictcomp>
    counts = {c : {o : form(het(c[1])[o][0][0], het(c[1])[o][1][0], rcounts[c][o]) for o in rcounts[c]} for c in rcounts}
  File "/gpfs/gsfs9/users/Robinson-SB/SB-workflows/CN-analysis/.snakemake/conda/c11c9886ddd3e3591e5ea64c07573fac/lib/python3.9/site-packages/hatchet/utils/count_alleles.py", line 60, in <dictcomp>
    counts = {c : {o : form(het(c[1])[o][0][0], het(c[1])[o][1][0], rcounts[c][o]) for o in rcounts[c]} for c in rcounts}
KeyError: 89850
``` 

Best, Welles

**Comment by brian-arnold** [comment]
Hi Welles,
Please try using the latest release of HATCHet, v0.4.10. This should resolve this issue!
Sincerely,
Brian

**Comment by wir963** [comment]
Hey Brian, 

Thanks for getting back to me - I'll try that once HATCHet v0.4.10 is available on bioconda and let you know if it's resolved.

Best, Welles

**Comment by wir963** [comment]
Confirming that upgrading to v0.4.10 fixes this issue. 

Best, Welles
