### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by mdiaz09** [raphael-group/hatchet#117]
Hello, 

I am attempting to run HATCHet with the demo dataset and .ini file and followed the complete demo code after installing HATCHet in it's own conda environment. Once the demo attempts to perform 
# Writing the list of selected SNPs, covered and heterozygous in the normal sample
I encounter the following error

Traceback (most recent call last):
  File "/Users/diazm6/miniconda3/envs/hatchet/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/diazm6/miniconda3/envs/hatchet/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/diazm6/miniconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/__main__.py", line 65, in <module>
    sys.exit(main())
  File "/Users/diazm6/miniconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/__main__.py", line 61, in main
    globals()[command](args)
  File "/Users/diazm6/miniconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/utils/run.py", line 89, in main
    count_alleles(
  File "/Users/diazm6/miniconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/utils/count_alleles.py", line 40, in main
    with open(hetsnpsfiles[chro], 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output/output/tmpy5444p9k/TMP_chr1.tsv'

any suggestions on how to proceed would be greatly appreciated.

**Comment by vineetbansal** [comment]
Hi @mdiaz09 - thanks for bringing this to our attention. This was indeed a bug introduced recently, which we have now fixed in HATCHet v0.4.11 (available on Bioconda and Github Releases). I'll close this ticket but feel free to open it if this is still an issue.

**Comment by mdiaz09** [comment]
I believe this is an ongoing issue, but I may be wrong. I have installed HATCHet in a conda environment and calling < conda list > shows that I have v0.4.11 but if I call < hatchet > with no input I am given the following response 
`HATCHet v0.4.9
Usage: hatchet <command> <arguments ..>

The following commands are supported:
 count-reads
 genotype-snps
 count-alleles
 combine-counts
 cluster-bins
 plot-bins
 compute-cn
 plot-cn
 check-solver
 run
`
and [Errno 2] continues to exist
