### ISSUE TITLE
Issue encountered in demo for the entire HATCHet pipeline

### ISSUE THREAD

**Issue by gurbaaz27** [raphael-group/hatchet#153]
Hi! I have been following the full HATCHet pipeline demo provided [here](http://compbio.cs.brown.edu/hatchet/examples/demo-complete/demo-complete.html), but I faced an error of `ValueError(error('No SNPs found in the normal!\n'))` on running the final command `python -m hatchet hatchet.ini`. I have done [manual installation](http://compbio.cs.brown.edu/hatchet/doc_manual_install.html) for HATCHet and downloaded and used the same `bam` and `fa` files as mentioned in demo. I suspect outdated demo tutorial to be the reason for failure, but I could be wrong. I would appreciate any inputs or solutions! Thanks.

**Error (ignore the debug print messages)**

```
[2022-Aug-14 10:23:00]('# Parsing the input arguments, checking the consistency of given files, and extracting required ', 'information\n')
	normal: ('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal')
	chromosomes: ['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22', 'chrX', 'chrY']
	samtools: samtools
	bcftools: bcftools
	snps: https://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh37p13/VCF/GATK/00-All.vcf.gz
	reference: data/hg19.fa
	j: 8
	q: 0
	Q: 11
	E: False
	mincov: 8
	maxcov: 300
	outputsnps: /home/gurbaaz/work/hatchet/output/snps
	verbose: False
[2022-Aug-14 10:24:03]# Inferring SNPs from the normal sample
next task
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr1')
Progress: |----------------------------------------| 0.0% Complete [[2022-Aug-14 10:24:03]Caller-1 starts on Normal for chr1)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
next task
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr2')
Progress: |----------------------------------------| 0.0% Complete [[2022-Aug-14 10:24:03]Caller-2 starts on Normal for chr2)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
next task
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr3')
Progress: |----------------------------------------| 0.0% Complete [[2022-Aug-14 10:24:03]Caller-3 starts on Normal for chr3)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
next task
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr4')
Progress: |----------------------------------------| 0.0% Complete [[2022-Aug-14 10:24:03]Caller-4 starts on Normal for chr4)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
codes
codes
codes
codes
next task
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr5')
Progress: |----------------------------------------| 0.0% Complete [[2022-Aug-14 10:24:03]Caller-5 starts on Normal for chr5)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
codes
next task
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr6')
Progress: |----------------------------------------| 0.0% Complete [[2022-Aug-14 10:24:03]Caller-6 starts on Normal for chr6)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
codes
next task
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr7')
Progress: |----------------------------------------| 0.0% Complete [[2022-Aug-14 10:24:03]Caller-7 starts on Normal for chr7)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
codes
next task
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr8')
Progress: |----------------------------------------| 0.0% Complete [[2022-Aug-14 10:24:03]Caller-8 starts on Normal for chr8)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
codes
[255, 0]
[255, 0]
[255, 0]
[255, 0]
[255, 0]
[255, 0]
[255, 0]
[255, 0]
Progress: |██████----------------------------------| 8.3% Complete [[2022-Aug-14 10:24:45]Caller-7 ends on Normal for chr7)]next task
next task
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr10')
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr9')
Progress: |██████----------------------------------| 16.7% Complete [[2022-Aug-14 10:24:45]Caller-2 starts on Normal for chr10)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
Progress: |██████----------------------------------| 16.7% Complete [[2022-Aug-14 10:24:45]Caller-5 starts on Normal for chr9)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
next task
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr11')
next task
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr12')
Progress: |██████----------------------------------| 16.7% Complete [[2022-Aug-14 10:24:45]Caller-6 starts on Normal for chr11)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
Progress: |██████----------------------------------| 16.7% Complete [[2022-Aug-14 10:24:45]Caller-7 starts on Normal for chr12)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
codes
codes
codes
[255, 0]
codes
[255, 0]
[255, 0]
[255, 0]
Progress: |███████████-----------------------------| 29.2% Complete [[2022-Aug-14 10:24:45]Caller-8 ends on Normal for chr8)]next task
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr13')
next task
Progress: |█████████████---------------------------| 33.3% Complete [[2022-Aug-14 10:24:45]Caller-4 starts on Normal for chr13)]('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr14')
====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
Progress: |█████████████---------------------------| 33.3% Complete [[2022-Aug-14 10:24:45]Caller-8 starts on Normal for chr14)]====================
next task
/home/gurbaaz/work/hatchet/data/normal.bam
====================
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr15')
Progress: |█████████████---------------------------| 33.3% Complete [[2022-Aug-14 10:24:45]Caller-3 starts on Normal for chr15)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
codes
codes
codes
[255, 0]
[255, 0]
[255, 0]
next task
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr16')
Progress: |█████████████---------------------------| 33.3% Complete [[2022-Aug-14 10:24:45]Caller-1 starts on Normal for chr16)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
codes
[255, 0]
Progress: |███████████████-------------------------| 37.5% Complete [[2022-Aug-14 10:25:09]Caller-2 ends on Normal for chr10)]next task
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr17')
Progress: |███████████████-------------------------| 37.5% Complete [[2022-Aug-14 10:25:09]Caller-2 starts on Normal for chr17)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
codes
[255, 0]
Progress: |████████████████------------------------| 41.7% Complete [[2022-Aug-14 10:25:09]Caller-4 ends on Normal for chr13)]next task
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr18')
Progress: |████████████████------------------------| 41.7% Complete [[2022-Aug-14 10:25:09]Caller-4 starts on Normal for chr18)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
codes
[255, 0]
Progress: |██████████████████----------------------| 45.8% Complete [[2022-Aug-14 10:25:10]Caller-5 ends on Normal for chr9)]next task
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr19')
Progress: |██████████████████----------------------| 45.8% Complete [[2022-Aug-14 10:25:10]Caller-5 starts on Normal for chr19)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
codes
[255, 0]
Progress: |████████████████████--------------------| 50.0% Complete [[2022-Aug-14 10:25:10]Caller-7 ends on Normal for chr12)]next task
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr20')
Progress: |████████████████████--------------------| 50.0% Complete [[2022-Aug-14 10:25:10]Caller-7 starts on Normal for chr20)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
codes
[255, 0]
Progress: |█████████████████████-------------------| 54.2% Complete [[2022-Aug-14 10:25:10]Caller-6 ends on Normal for chr11)]next task
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr21')
Progress: |█████████████████████-------------------| 54.2% Complete [[2022-Aug-14 10:25:10]Caller-6 starts on Normal for chr21)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
codes
[255, 0]
Progress: |███████████████████████-----------------| 58.3% Complete [[2022-Aug-14 10:25:10]Caller-8 ends on Normal for chr14)]next task
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chr22')
Progress: |███████████████████████-----------------| 58.3% Complete [[2022-Aug-14 10:25:10]Caller-8 starts on Normal for chr22)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
codes
[255, 0]
Progress: |█████████████████████████---------------| 62.5% Complete [[2022-Aug-14 10:25:10]Caller-1 ends on Normal for chr16)]next task
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chrX')
Progress: |█████████████████████████---------------| 62.5% Complete [[2022-Aug-14 10:25:10]Caller-1 starts on Normal for chrX)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
codes
[255, 0]
Progress: |██████████████████████████--------------| 66.7% Complete [[2022-Aug-14 10:25:10]Caller-3 ends on Normal for chr15)]next task
('/home/gurbaaz/work/hatchet/data/normal.bam', 'Normal', 'chrY')
Progress: |██████████████████████████--------------| 66.7% Complete [[2022-Aug-14 10:25:10]Caller-3 starts on Normal for chrY)]====================
/home/gurbaaz/work/hatchet/data/normal.bam
====================
codes
[255, 0]
Progress: |████████████████████████████------------| 70.8% Complete [[2022-Aug-14 10:25:32]Caller-6 ends on Normal for chr21)]next task
None
Progress: |██████████████████████████████----------| 75.0% Complete [[2022-Aug-14 10:25:33]Caller-2 ends on Normal for chr17)]next task
None
Progress: |███████████████████████████████---------| 79.2% Complete [[2022-Aug-14 10:25:33]Caller-5 ends on Normal for chr19)]next task
None
Progress: |█████████████████████████████████-------| 83.3% Complete [[2022-Aug-14 10:25:33]Caller-8 ends on Normal for chr22)]next task
None
Progress: |███████████████████████████████████-----| 87.5% Complete [[2022-Aug-14 10:25:33]Caller-4 ends on Normal for chr18)]next task
None
Progress: |████████████████████████████████████----| 91.7% Complete [[2022-Aug-14 10:25:33]Caller-7 ends on Normal for chr20)]next task
None
Progress: |██████████████████████████████████████--| 95.8% Complete [[2022-Aug-14 10:25:33]Caller-3 ends on Normal for chrY)]next task
None
Progress: |████████████████████████████████████████| 100.0% Complete [[2022-Aug-14 10:25:33]Caller-1 ends on Normal for chrX)]
next task
None
[2022-Aug-14 10:25:33]# Counting number of identified SNPs
No SNPs found in the normal!
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/gurbaaz/work/hatchet/venv/lib/python3.10/site-packages/hatchet/__main__.py", line 65, in <module>
    sys.exit(main())
  File "/home/gurbaaz/work/hatchet/venv/lib/python3.10/site-packages/hatchet/__main__.py", line 61, in main
    globals()[command](args)
  File "/home/gurbaaz/work/hatchet/venv/lib/python3.10/site-packages/hatchet/utils/run.py", line 110, in main
    genotype_snps(
  File "/home/gurbaaz/work/hatchet/venv/lib/python3.10/site-packages/hatchet/utils/genotype_snps.py", line 65, in main
    raise ValueError(error('No SNPs found in the normal!\n'))
ValueError: None
```

**System** 

```
OS: Ubuntu 20.04 (Linux 5.15.0-43-generic x86_64)
python version: 3.10.4
```

**hatchet.ini**

My `hatchet.ini` content (I am using only one tumour `.bam` here, as opposed to 3 files given in the demo)

```
[run]
genotype_snps=True
count_alleles=True
count_reads=True
combine_counts=True
cluster_bins=True
plot_bins=True
compute_cn=True
plot_cn=True
reference=data/hg19.fa
output=output/
processes=8
normal=data/normal.bam
bams=data/bulk_03clone1_06clone0_01normal.sorted.bam
samples=TumorSample1
[genotype_snps]
mincov=8
maxcov=300
reference_version=hg19
chr_notation=True
[count_alleles]
mincov=8
maxcov=300
[combine_counts]
msr=3000
mtr=5000
```

**Comment by brian-arnold** [comment]
Hi Gurbaaz, 
Thanks for your post. I'm currently looking into this to try to replicate this error, but I just wanted to mention that a similar error has popped up in a [previous issue](https://github.com/raphael-group/hatchet/issues/120) in case this helps solve your problem. If hatchet doesn't have internet access, it cannot access a file containing a list of known germline variant so it can simply be downloaded manually.

In any case, I'll follow up fully once I can reproduce your error message on my end.
Brian

**Comment by vineetbansal** [comment]
Hi @gurbaaz27 - `HATCHet 1.1.0` fixes this issue with the demo. This version should be available on `bioconda` soon, but since you're doing a manual installation in your case, you may want to check it out sooner from the `master` branch or `releases`.

See the updated documentation at:
https://compbio.cs.brown.edu/hatchet/script/README.html#command-for-running-the-hatchet-workflow

Essentally, setting the key `[run].chromosomes` (or the env var `HATCHET_RUN_CHROMOSOMES`) to `chr22` should allow you to run the demo to completion.
