### ISSUE TITLE
solve steps fails with GRBException

### ISSUE THREAD

**Issue by SebastianHollizeck** [raphael-group/hatchet#16]
Hi,

I have followed the workflow described originally in the bash script and then in the md file.

Everything seems to work until the solve step, which fails after a few seconds with this message ( i shortened it a bit, but can add the whole thing if that is interesting.)

```
# Finding the neutral diploid/tetraploid cluster
## Cluster selected as neutral (diploid/tetraploid) is 29
# Running diploid
## Running diploid with 2 clones
### Running command: /home/shollizeck/hatchet/lib/python2.7/site-packages/hatchet-0.1.0-py2.7-linux-x86_64.egg/hatchet/solve /home/shollizeck/test_hatchet//bbc/bulk -f  -e 6 -j 2 -p 400 -u 0.03 -r 12 -M 2 -v 2 -c 29:1:1 -n 2 -o /home/shollizeck/test_hatchet//results/results.diploid.n2
## M:	2
## mR:	0.08
## mB:	0.04
## m:	None
## clonal:	None
## tR:	0.08
## seg:	/home/shollizeck/test_hatchet//bbc/bulk.seg
## tetraploid:	False
## diploid:	False
## eT:	12
## r:	12
## tB:	0.04
## u:	0.03
## x:	/home/shollizeck/test_hatchet//results
## f:	None
## d:	None
## g:	0.35
## solver:	/home/shollizeck/hatchet/lib/python2.7/site-packages/hatchet-0.1.0-py2.7-linux-x86_64.egg/hatchet/solve
## ln:	2
## eD:	6
## j:	2
## bbc:	/home/shollizeck/test_hatchet//bbc/bulk.bbc
## ts:	0.008
## p:	400
## s:	None
## un:	8
## limit:	0.6
## v:	3
## input:	/home/shollizeck/test_hatchet//bbc/bulk
## td:	0.1
## ampdel:	True
## tc:	1
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/shollizeck/hatchet/lib/python2.7/site-packages/hatchet-0.1.0-py2.7-linux-x86_64.egg/hatchet/__main__.py", line 45, in <module>
    solve([solve_bin] + args)
  File "/home/shollizeck/hatchet/lib/python2.7/site-packages/hatchet-0.1.0-py2.7-linux-x86_64.egg/hatchet/bin/HATCHet.py", line 189, in main
    diploidObjs = runningDiploid(neutral=neutral, args=args)
  File "/home/shollizeck/hatchet/lib/python2.7/site-packages/hatchet-0.1.0-py2.7-linux-x86_64.egg/hatchet/bin/HATCHet.py", line 378, in runningDiploid
    results.append((n , execute(args, basecmd, n, outprefix), outprefix))
  File "/home/shollizeck/hatchet/lib/python2.7/site-packages/hatchet-0.1.0-py2.7-linux-x86_64.egg/hatchet/bin/HATCHet.py", line 641, in execute
    raise RuntimeError(error("The following command failed: \n\t\t{}\nwith {}\n".format(cmd, buffer)))
RuntimeError: The following command failed: 
		/home/shollizeck/hatchet/lib/python2.7/site-packages/hatchet-0.1.0-py2.7-linux-x86_64.egg/hatchet/solve /home/shollizeck/test_hatchet//bbc/bulk -f  -e 6 -j 2 -p 400 -u 0.03 -r 12 -M 2 -v 2 -c 29:1:1 -n 2 -o /home/shollizeck/test_hatchet//results/results.diploid.n2
with ['\x1b[95m\x1b[1m[21:06:31]### Parsing and checking input arguments\t\x1b[0m', '\x1b[92m[21:06:31]## \tInput prefix:  /home/shollizeck/test_hatchet//bbc/bulk', 'Input SEG:  /home/shollizeck/test_hatchet//bbc/bulk.seg', 'Input BBC:  /home/shollizeck/test_hatchet//bbc/bulk.bbc', 'Number of clones:  2', 'Clonal copy numbers:  { 29 [Cluster] : 1|1 [CN] }', 'Help message:  0', 'Maximum number of copy-number states:  -1', 'Maximum integer copy number:  6', 'Number of jobs:  2', 'Number of seeds:  400', 'Minimum tumor-clone threshold:  0.03', 'Maximum resident memory:  -1', 'Time limit:  -1', 'Maximum number of iteratios:  10', 'Random seed:  12', 'Solving mode:  Coordinate-descent only', 'Verbose:  2', 'Output prefix:  /home/shollizeck/test_hatchet//results/results.diploid.n2', 'Diploid threshold:  0.1', 'Base:  1', 'Force amp-del:  1\t\x1b[0m', '\x1b[95m\x1b[1m[21:06:31]### Reading the input SEG file\t\x1b[0m', '\x1b[95m\x1b[1m[21:06:31]### Scale the read-depth ratios into fractional copy numbers using the provided copy numbers\t\x1b[0m', '\x1b[95m\x1b[1m[21:06:31]### Compute allele-specific fractional copy numbers using BAF\t\x1b[0m', '\x1b[95m\x1b[1m[21:06:31]### Starting coordinate descent algorithm on 400 seeds\t\x1b[0m', '\x1b[92m[21:06:31]## Coordinate Descence {\t\x1b[0m', "terminate called after throwing an instance of 'GRBException'", '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

```

I just dont even know where to do something different, so any help/fix would be amazing.

Cheers,
Sebastian

**Comment by vineetbansal** [comment]
Hi @SebastianHollizeck .. in my experience `GRBExceptions` are almost exclusively caused by Gurobi Licensing issues. After getting a valid license from Gurobi and setting `GUROBI_HOME`, you're supposed to point the environment variable `GRB_LICENSE_FILE` to the `gurobi.lic` file that you must have obtained from them - especially if it happens to sit in a non-home location (See https://github.com/raphael-group/hatchet#using-gurobi).

There's one test you can use to isolate this problem. If you've cloned the repo and are at the same level as the `tests` folder, you can use `pytest` to run some basic sanity tests. In your case:

```
pip install pytest
pytest tests/test_solver.py -rA
```
In your case, since you're experiencing unrelated pip-issues, you may explicitly want to specify `pip install pytest==4.6.11` in the first line.

If the test passes (should be really quick), then your Gurobi installation is working fine. If it fails (or is skipped over), then there's a problem.

Also - since you've taken the time to run the sample bash script, you may want to save your intermediate outputs (and comment out the lines in the script that try to overwrite them) to avoid having to go through the whole process again.

**Comment by SebastianHollizeck** [comment]
Hi,

it seems like a license issue, just as you suggested.
I have a single bound license installed on a specific node on our HPC, which i am using until we might get an institutional license.

I requested the license on the same node, and the node also appears on the gurobi homepage, so it seems to have activated.

So i tried to run the test with the environmental variables set
```
(hatchet) [shollizeck@vmdv-res-cluster1 ~]$ GRB_LICENSE_FILE=/home/shollizeck/hatchet_deps/.licenses/gurobi_vmdv-res-cluster.lic
(hatchet) [shollizeck@vmdv-res-cluster1 ~]$ GUROBI_HOME=/home/shollizeck/hatchet_deps/gurobi903/
(hatchet) [shollizeck@vmdv-res-cluster1 ~]$ ll $GRB_LICENSE_FILE 
-rw-rw-r-- 1 shollizeck shollizeck 229 Sep 25 13:15 /home/shollizeck/hatchet_deps/.licenses/gurobi_vmdv-res-cluster.lic
(hatchet) [shollizeck@vmdv-res-cluster1 ~]$ ll $GUROBI_HOME 
total 1.0K
drwxrwxr-x 10 shollizeck shollizeck 512 Aug 27 10:05 linux64
(hatchet) [shollizeck@vmdv-res-cluster1 ~]$ pytest hatchet_deps/hatchet/tests/test_solver.py -rA
=========================================================================================== test session starts ============================================================================================
platform linux2 -- Python 2.7.5, pytest-4.6.11, py-1.9.0, pluggy-0.13.1
rootdir: /home/shollizeck/hatchet_deps/hatchet
collected 1 item                                                                                                                                                                                           

hatchet_deps/hatchet/tests/test_solver.py s                                                                                                                                                          [100%]

========================================================================================= short test summary info ==========================================================================================
SKIPPED [1] tests/test_solver.py:11: No license for Gurobi found
======================================================================================== 1 skipped in 1.07 seconds =========================================================================================
```

however when i export the variables it actually works.
```
(hatchet) [shollizeck@vmdv-res-cluster1 ~]$ export GUROBI_HOME=/home/shollizeck/hatchet_deps/gurobi903/
(hatchet) [shollizeck@vmdv-res-cluster1 ~]$ export GRB_LICENSE_FILE=/home/shollizeck/hatchet_deps/.licenses/gurobi_vmdv-res-cluster.lic
(hatchet) [shollizeck@vmdv-res-cluster1 ~]$ pytest hatchet_deps/hatchet/tests/test_solver.py -rA
=========================================================================================== test session starts ============================================================================================
platform linux2 -- Python 2.7.5, pytest-4.6.11, py-1.9.0, pluggy-0.13.1
rootdir: /home/shollizeck/hatchet_deps/hatchet
collected 1 item                                                                                                                                                                                           

hatchet_deps/hatchet/tests/test_solver.py .                                                                                                                                                          [100%]

================================================================================================== PASSES ==================================================================================================
_______________________________________________________________________________________________ test_solver ________________________________________________________________________________________________
------------------------------------------------------------------------------------------- Captured stdout call -------------------------------------------------------------------------------------------
/home/shollizeck/hatchet/lib/python2.7/site-packages/hatchet-0.1.0-py2.7-linux-x86_64.egg/hatchet/solve /home/shollizeck/hatchet_deps/hatchet/tests/data/bulk -f -e 6 -p 400 -u 0.03 -r 6700 -M 1 -v 2 -c 1:1:1 -n 2
========================================================================================= short test summary info ==========================================================================================
PASSED hatchet_deps/hatchet/tests/test_solver.py::test_solver
========================================================================================= 1 passed in 2.40 seconds =========================================================================================

```

so that seems to be the solution here.

**Comment by karini925** [comment]
Hi there, 

I experienced the same error and it seems the issue is resolved/the test passes if I use a node on the HPC cluster that has an internet connection. Do have any suggestion for what I should do if I am using a node with no internet connection? 

Thanks!

Karin

**Comment by simozacca** [comment]
@karini925 Thank you for the interest in HATCHet. The error is due an issue with the Gurobi license and the solution/issue depends on whether you are using a machine/individual-specific license or a license server in a computing cluster:

- if you are using a license server, this works such that there is a program 'running' in the cluster which will provide a license every time you request to use Gurobi in any machine of the cluster. This server might require an active internet connection (not sure 100%) but any related issue/solution should be discussed with the administrator of the cluster, as it is cluster-dependent;

- if you are using a machine/individual specific license, this does not require any internet connection but only the license file that you activated. However such license can only be used on the exact machine where you activated (and only be used by the user that activated it). Thus this is a feasible solution only if you can always access the same server (for which you can store the specific license in a file).

**Comment by rgold97** [comment]
Hi!! I've come across the same issue at the solve portion of the WES demo. I have a WLS (floating web) academic license for Gurobi and have annotated the proper paths to point to that license and the gurobi home directory. I am trying to run this from a docker image in a google VM but can't get out of this error. Any advice here? 

Thanks so much!! 
-Rose

<img width="905" alt="Screen Shot 2021-02-17 at 3 21 53 PM" src="https://user-images.githubusercontent.com/28493357/108263151-deca4200-7133-11eb-859a-5a040dd57e98.png">

**Comment by vineetbansal** [comment]
@rgold97 .. that seems to be a Gurobi licensing issue that we've encountered as well. The academic license doesn't seem to work inside a docker container, and my understanding is that it requires you to set up a token license server *outside* the running container. More information here - https://support.gurobi.com/hc/en-us/articles/360040044712
