### ISSUE TITLE
the step "phase_snps" error

### ISSUE THREAD

**Issue by DecodeGenome** [raphael-group/hatchet#170]
Hi hatchet developers:

I ran " python3 -m hatchet run hatchet.ini", it created "snps" folder in "output", then the error occured below, how to fix it?

Thanks,

Wei

The step "phase_snps" requires that the config variable "download_panel.refpaneldir" indicates the directory where the reference panel is located.Traceback (most recent call last):
  File "/wynton/home/bivona/wwu888/anaconda3/envs/hatchet112/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/wynton/home/bivona/wwu888/anaconda3/envs/hatchet112/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/wynton/home/bivona/wwu888/anaconda3/envs/hatchet112/lib/python3.9/site-packages/hatchet/__main__.py", line 65, in <module>
    sys.exit(main())
  File "/wynton/home/bivona/wwu888/anaconda3/envs/hatchet112/lib/python3.9/site-packages/hatchet/__main__.py", line 61, in main  
    globals()[command](args)
  File "/wynton/home/bivona/wwu888/anaconda3/envs/hatchet112/lib/python3.9/site-packages/hatchet/utils/run.py", line 145, in main
    raise ValueError(
ValueError: The step "phase_snps" requires that the config variable "download_panel.refpaneldir" indicates the directory where the reference panel is located.

**Comment by brian-arnold** [comment]
Hi Wei,
Could you provide a copy of your hatchet.ini file here? At first glance it looks like the first step to download the reference panel may not have been done, or the path of the panel (located in the download_panel.refpaneldir variable) was not specified.
Sincerely,
Brian

**Comment by DecodeGenome** [comment]
Hi Brian,

I worked on HPC server, I realized that I don't have multi-user gurobi license.

Now I am trying to work on my macbook pro laptop (Monterey 12.6), I installed hatchet 1.1.2 and Gurobi952. After "hatchet check", there is a new issue now. I checkd mosdepth, it was installed under my "hatchet" environment. (

(hatchet) WilliamWus-MacBook-Pro:UCSF500_WGD_HATCHET cancerbio$ which mosdepth

/opt/anaconda3/envs/hatchet/bin/mosdepth

(hatchet) WilliamWus-MacBook-Pro:UCSF500_WGD_HATCHET cancerbio$ python -V

Python 3.10.6


) Then I added the "config.paths.mosdepth" in hatchet.ini (see attachment), it still had issue (below).  Could please look into this issue?

The samples I am using are targeted exome sequencing, is there any specific setting for targeted exome sequencing in hatchet.ini? where to add panel bed filed in the hatchet.ini file?

I also tried to install hatchet with conda or manually on M1 max mac,  none of them work. Do you have new version of hatchet that is compatible with M1 chip?

I desperately want to get hatchet algorithm working for our research projects, Please help me out.

Thanks,

Wei
######################################
mosdepth check FAILED.
    Please install mosdepth executable and either ensure its on your
    PATH, or its location specified in hatchet.ini as
    config.paths.mosdepth, or its location specified using the
    environment variable HATCHET_PATHS_MOSDEPTH
########################################
## error after hatchet run hatchet.ini


[2022-Oct-31 23:08:37]# Writing the allele counts of tumor samples for selected SNPs

[2022-Oct-31 23:08:37]# Parsing and checking input arguments

The mosdepth executable was not found or is not executable. Please install mosdepth (e.g., conda install -c bioconda mosdepth) and/or supply the path to the executable.Traceback (most recent call last):

  File "/opt/anaconda3/envs/hatchet/lib/python3.10/runpy.py", line 196, in _run_module_as_main

    return _run_code(code, main_globals, None,

  File "/opt/anaconda3/envs/hatchet/lib/python3.10/runpy.py", line 86, in _run_code

    exec(code, run_globals)

  File "/opt/anaconda3/envs/hatchet/lib/python3.10/site-packages/hatchet/__main__.py", line 65, in <module>

    sys.exit(main())

  File "/opt/anaconda3/envs/hatchet/lib/python3.10/site-packages/hatchet/__main__.py", line 61, in main

    globals()[command](args)

  File "/opt/anaconda3/envs/hatchet/lib/python3.10/site-packages/hatchet/utils/run.py", line 202, in main

    count_reads(

  File "/opt/anaconda3/envs/hatchet/lib/python3.10/site-packages/hatchet/utils/count_reads.py", line 20, in main

    args = parse_count_reads_args(args)

  File "/opt/anaconda3/envs/hatchet/lib/python3.10/site-packages/hatchet/utils/ArgParsing.py", line 584, in parse_count_reads_args

    ensure(

  File "/opt/anaconda3/envs/hatchet/lib/python3.10/site-packages/hatchet/utils/Supporting.py", line 147, in ensure

    return error(msg, raise_exception=True, exception_class=exception_class)

  File "/opt/anaconda3/envs/hatchet/lib/python3.10/site-packages/hatchet/utils/Supporting.py", line 137, in error

    return log(

  File "/opt/anaconda3/envs/hatchet/lib/python3.10/site-packages/hatchet/utils/Supporting.py", line 124, in log

    raise exception_class(msg)

ValueError: The mosdepth executable was not found or is not executable. Please install mosdepth (e.g., conda install -c bioconda mosdepth) and/or supply the path to the executable.

(hatchet) WilliamWus-MacBook-Pro:UCSF500_WGD_HATCHET cancerbio$

________________________________

**Comment by vineetbansal** [comment]
@DecodeGenome - the `hatchet check` command (when it comes to checking `mosdepth`) is essentially just trying to run `mosdepth --version` and making sure that the return code is `0`. Can you confirm if this is indeed the case? I just installed `mosdepth` from the `bioconda` channel (version `0.3.3`) and it does work (as does `hatchet check` for `mosdepth`).
