### ISSUE TITLE
ValueError: None potential neutral cluster found with given parameters!

### ISSUE THREAD

**Issue by DecodeGenome** [raphael-group/hatchet#174]
Hi,

I am running targeted genomic sequencing for hatchet analysis (hatchet run hatchet.ini), 2 out of 3 samples, at the end, i got the error below, could you please let me know what is the possible causes? 

Thanks,

Wei

# Finding the neutral diploid/tetraploid cluster
Traceback (most recent call last):
  File "/wynton/home/bivona/wwu888/anaconda3/envs/hatchet112/bin/hatchet", line 33, in <module>
    sys.exit(load_entry_point('hatchet==1.1.1', 'console_scripts', 'hatchet')())
  File "/wynton/home/bivona/wwu888/anaconda3/envs/hatchet112/lib/python3.9/site-packages/hatchet/__main__.py", line 61, in main
    globals()[command](args)
  File "/wynton/home/bivona/wwu888/anaconda3/envs/hatchet112/lib/python3.9/site-packages/hatchet/utils/run.py", line 370, in main
    hatchet_main(args=['-x', f'{output}/results', '-i', f'{output}/bbc/bulk'] + extra_args)
  File "/wynton/home/bivona/wwu888/anaconda3/envs/hatchet112/lib/python3.9/site-packages/hatchet/bin/HATCHet.py", line 457, in main
    neutral = findNeutralCluster(seg=fseg, size=size, td=args['td'], samples=samples, v=args['v'])
  File "/wynton/home/bivona/wwu888/anaconda3/envs/hatchet112/lib/python3.9/site-packages/hatchet/bin/HATCHet.py", line 770, in findNeutralCluster
    raise ValueError(error('None potential neutral cluster found with given parameters!'))
ValueError: None potential neutral cluster found with given parameters!

**Comment by simozacca** [comment]
Thank you for your question. HATCHet requires the idetification of at least one allelic-balanced segment (either diploid or tetraploid); the errors indicates that no segment could be identified as such with the maximum default threshold of 0.08 of difference for BAF from the neutral value of 0.5. So you could try to re-run (starting from the clustering step rather than re-running everything) by using a higher value. For related details, pelase refer to the dedicated tutorial "Bias in balanced BAF" at: http://compbio.cs.brown.edu/hatchet/recommendation_datatype.html 

Also if you could upload your intermediate plots, especially clustered_bb plot or similar we could help you to interpret your data. In fact, what type of target data are you working on? We have successfully applied HATCHet to WES data, but it might not work with any form of more targeted data.

**Comment by vaibhakv** [comment]
Hi DecodeGenome.
Did it work for targeted data?

Thanks,
Vaibhav
