### ISSUE TITLE
tabix parse error and cluster-bins failure

### ISSUE THREAD

**Issue by csmoreno** [raphael-group/hatchet#188]
Consistently getting a tabix parse error
"[W::tbx_parse1] Coordinate <= 0 detected. Did you forget to use the -0 option?"

and also getting this error which kills the pipeline at the cluster-bins step:

[0mTraceback (most recent call last):
  File "/opt/scratchspace/cmoreno/anaconda3/envs/hatchet/bin/hatchet", line 8, in <module>
    sys.exit(main())
  File "/opt/scratchspace/cmoreno/anaconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/__main__.py", line 61, in main
    globals()[command](args)
  File "/opt/scratchspace/cmoreno/anaconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/utils/run.py", line 316, in main
    cluster_bins(
  File "/opt/scratchspace/cmoreno/anaconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/utils/cluster_bins.py", line 71, in main
    assert str(start_row[0]) == my_chr, (start_row[0], my_chr)
AssertionError: ('chr1', "('chr1',)")

Any help is much appreciated. Thanks

**Comment by ronkesm** [comment]
Were you able to troubleshoot this? I can circumvent the error by using the (deprecated?) `cluster-bins-gmm` but then it fails on the `compute-cn` instead (Raised here #193 ). I also get the tabix error preceding this.

**Comment by tmfreeman400** [comment]
Were either of you able to solve the error in cluster-bins in the end? If so, did you determine what the cause was? I am also getting the same error:
`    assert str(start_row[0]) == my_chr, (start_row[0], my_chr)
AssertionError: ('chr1', "('chr1',)")
`

I also had text in cluster-bins error log indicating that the model was not converging, in case this is related:
"Model is not converging.  Current: 21469.297836887617 is not greater than 21469.305961301663. Delta is -0.008124414045596495"

Any help would be greatly appreciated.

**Comment by csmoreno** [comment]
I had a real challenge working through this.  What I ended up doing was running the first half of the analysis with version 1.2.1 until I get this error, and then taking the output files from the point of this error and running them through the rest of the pipeline using version 1.1.1.  I did have to reformat the bulk.bb files to have the correct columns and order of chromosomes.  However, they have now released version 2.0.1, so hopefully the issue has been resolved.

From: Tim Freeman ***@***.***>
Date: Thursday, December 21, 2023 at 6:31 PM
To: raphael-group/hatchet ***@***.***>
Cc: Moreno, Carlos S ***@***.***>, Author ***@***.***>
Subject: [External] Re: [raphael-group/hatchet] tabix parse error and cluster-bins failure (Issue #188)

Were either of you able to solve the error in cluster-bins in the end? If so, did you determine what the cause was? I am also getting the same error:
assert str(start_row[0]) == my_chr, (start_row[0], my_chr) AssertionError: ('chr1', "('chr1',)")

I also had text in cluster-bins error log indicating that the model was not converging, in case this is related:
"Model is not converging. Current: 21469.297836887617 is not greater than 21469.305961301663. Delta is -0.008124414045596495"

Any help would be greatly appreciated.

**Comment by tmfreeman400** [comment]
Thank you very much for your fast response csmoreno! The issue has indeed been resolved with the new version (2.0.1) and the error isn't happening anymore. :)
