### ISSUE TITLE
Failed to parse the output of the following command because the final objective was not found: {cmd}

### ISSUE THREAD

**Issue by ronkesm** [raphael-group/hatchet#193]
[](url)Hi,

I am currently trying to run hatchet (v1.1.1) on two WGS samples from a matched diagnosis-relapse experiment.

See .bbc + .seg files below (had to change file extensions to .txt to upload)

[pd41050.bbc.txt](https://github.com/raphael-group/hatchet/files/12411010/pd41050.bbc.txt)
[pd41050.seg.txt](https://github.com/raphael-group/hatchet/files/12411012/pd41050.seg.txt)

These were generated using cluster-bins-gmm

When I run:

`hatchet compute-cn -i bbc/pd41050`

It returns (irrespective of solver used, this run was with cbc. Tested with gurobi and glpk as well and the resulting error is the same):
```
## solver:      /home/ronas/mambaforge/envs/hatchet_2/bin/cbc
## input:       bbc/pd41050
## seg: bbc/pd41050.seg
## bbc: bbc/pd41050.bbc
## ln:  2
## un:  8
## clonal:      None
## ampdel:      True
## d:   None
## eD:  6
## eT:  12
## ts:  0.008
## tc:  1
## td:  0.01
## tR:  0.08
## tB:  0.04
## mR:  0.08
## mB:  0.04
## limit:       None
## g:   0.3
## p:   400
## j:   1
## r:   None
## s:   None
## m:   None
## u:   0.03
## f:   None
## M:   2
## x:   ./
## diploid:     False
## tetraploid:  False
## v:   2
## binwise:     False

        solver: /home/ronas/mambaforge/envs/hatchet_2/bin/cbc
        input: bbc/pd41050
        seg: bbc/pd41050.seg
        bbc: bbc/pd41050.bbc
        ln: 2
        un: 8
        clonal: None
        ampdel: True
        d: None
        eD: 6
        eT: 12
        ts: 0.008
        tc: 1
        td: 0.01
        tR: 0.08
        tB: 0.04
        mR: 0.08
        mB: 0.04
        limit: None
        g: 0.3
        p: 400
        j: 1
        r: None
        s: None
        m: None
        u: 0.03
        f: None
        M: 2
        x: ./
        diploid: False
        tetraploid: False
        v: 2
        binwise: False
# Reading and parsing clustered bins in BBC file
# Reading and parsing bin clusters in SEG file
# Computing the cluster sizes
# Filtering clusters based on covered genome size and covered chromosomes
# Selected clusters: 13, 1, 15, 12, 14, 9, 10
## Features of selected clusters:
## 13: SIZE= 52542432.0 #CHRS= 7        (RDR, BAF)= (0.9791477820494887, 0.5)-(0.7677874225954809, 0.3690169677622321)
## 1: SIZE= 2394291634.0        #CHRS= 21       (RDR, BAF)= (0.9654959915610395, 0.5)-(0.9603414481327959, 0.5)
## 15: SIZE= 40336009.0 #CHRS= 22       (RDR, BAF)= (1.0746900475678796, 0.45701409511367735)-(1.027077406604921, 0.44999780487046476)
## 12: SIZE= 41052631.0 #CHRS= 21       (RDR, BAF)= (1.0726643812061305, 0.491046803929593)-(1.0138931288353428, 0.49130034540261314)
## 14: SIZE= 127029534.0        #CHRS= 22       (RDR, BAF)= (0.9890242106872142, 0.46414739405770444)-(0.9737457297107248, 0.4538575419268043)
## 9: SIZE= 72347876.0  #CHRS= 4        (RDR, BAF)= (0.9684406179344259, 0.5)-(1.160067287349421, 0.429368440808576)
## 10: SIZE= 32552063.0 #CHRS= 1        (RDR, BAF)= (1.4660684487222975, 0.3346368159738641)-(1.4155828135536173, 0.3449056036166652)
# Finding the neutral diploid/tetraploid cluster
## Cluster selected as neutral (diploid/tetraploid) is 1
# Running diploid
## Running diploid with 2 clones
Traceback (most recent call last):
  File "/home/ronas/mambaforge/envs/hatchet_2/bin/hatchet", line 33, in <module>
    sys.exit(load_entry_point('hatchet==1.1.1', 'console_scripts', 'hatchet')())
  File "/home/ronas/mambaforge/envs/hatchet_2/lib/python3.9/site-packages/hatchet/__main__.py", line 61, in main
    globals()[command](args)
  File "/home/ronas/mambaforge/envs/hatchet_2/lib/python3.9/site-packages/hatchet/bin/HATCHet.py", line 460, in main
    diploidObjs = runningDiploid(neutral=neutral, args=args)
  File "/home/ronas/mambaforge/envs/hatchet_2/lib/python3.9/site-packages/hatchet/bin/HATCHet.py", line 793, in runningDiploid
    results.append((n, execute(args, basecmd, n, outprefix), outprefix))
  File "/home/ronas/mambaforge/envs/hatchet_2/lib/python3.9/site-packages/hatchet/bin/HATCHet.py", line 1145, in execute
    raise RuntimeError(
RuntimeError: Failed to parse the output of the following command because the final objective was not found:
                {cmd}
```

**Comment by teerjk** [comment]
I encountered the same error using the cbc solver and the 9226e44 commit (latest as of this writing). Not sure if I had the same cause, but in my case I forgot to set the solver variable:
`export HATCHET_COMPUTE_CN_SOLVER=cbc`

I also included the cbc bin on the command line:
`python -m hatchet compute-cn -i out /usr/bin/cbc`
Hope this helps.

**Comment by ronkesm** [comment]
Hi @teerjk, thanks so much for posting this. I am not encountering the bug after pointing to the cbc bin the end of the command via `usr/bin/cbc`. I had already set the solver variable so it was the second part that fixed it! 

For whatever reason, the same error occurs if I submit it as a job, but now it's at least able to run on the command line!
