### ISSUE TITLE
Length of values does not match length of index

### ISSUE THREAD

**Issue by tnyamaguchi** [raphael-group/hatchet#209]
Hello,

I encountered the following error at the `combine_counts` stage when processing multiple WGS samples.

```
[2024-Mar-11 11:36:47]Correcting haplotype switches on q arm...
Found haplotype switches in  37.11% of bins
Checking haplotype switching using [10] segments
Identified 7 segments with haplotype switching
Error in chromosome chr21:Length of values (1834) does not match length of index (1792)Traceback (most recent call last):
  File "/path/to/miniconda3/lib/python3.9/site-packages/hatchet/utils/combine_counts.py", line 1218, in run_chromosome
    bb_q['BAF'] = corrected_bafs_q.flatten()
  File "/path/to/miniconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 3656, in __setitem__
    self._set_item(key, value)
  File "/path/to/miniconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 3833, in _set_item
    value = self._sanitize_column(value)
  File "/path/to/miniconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 4537, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/path/to/miniconda3/lib/python3.9/site-packages/pandas/core/common.py", line 557, in require_length_match
    raise ValueError(
ValueError: Length of values (1834) does not match length of index (1792)
```

I've run the default stages with `fixed_width = False`. Otherwise, I'm essentially using the default settings. Any thoughts on this error?

```
genotype_snps = True
count_alleles = True
count_reads = True
phase_snps = True
fixed_width = False
```

**Comment by teerjk** [comment]
I am also seeing the same error in version 2.0.1 in the combine_counts step when using WES data. Interestingly, I only see the error when haplotype switching is found, but I have not set the --phase option. In my case, I can avoid the error by increasing --msr, but this gives suboptimal results. Any suggestions?

Error in chromosome chr20:ESC[0mESC[91mLength of values (260) does not match length of index (143)ESC[0mTraceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/hatchet/utils/combine_counts.py", line 1218, in run_chromosome
    bb_q['BAF'] = corrected_bafs_q.flatten()
  File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 3950, in __setitem__
    self._set_item(key, value)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 4143, in _set_item
    value = self._sanitize_column(value)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 4870, in _sanitize_column
    com.require_length_match(value, self.index)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/common.py", line 576, in require_length_match
    raise ValueError(
ValueError: Length of values (260) does not match length of index (143)

**Comment by RunpengLuo** [comment]
Hi @teerjk 

Do you mind to try the latest version 2.1.2 and see if the error persists? It is available on Conda as well. Thank you.

John

**Comment by teerjk** [comment]
@RunpengLuo, thank you! I just finished a test run with 2.1.2 and I did not have the issue this time. Interestingly, it looked like there were no haplotype switches found this time. Either way, it worked! I'll also note while I did see the "Coordinate <0" error mentioned in another issue, I am using an older Samtools/bcftools/htslib suite, and so only saw warnings (the run completed.)
Thanks again for the dev team efforts on this software!

**Comment by RunpengLuo** [comment]
Glad it worked out this time, I will close the issue now.
