### ISSUE TITLE
AssertionError at clustering step 

### ISSUE THREAD

**Issue by willhooper** [raphael-group/hatchet#216]
Hi, I'm trying to run Hatchet2 and I'm running into the following error at the clustering step:

```
[2024-Apr-17 21:15:57]# Merging per-chromosome bb files and correcting read counts
[2024-Apr-17 21:15:58]# Done
[2024-Apr-17 21:15:58]# Parsing and checking input arguments

	bbfile: /gpfs/commons/projects/landau_brain_mets/compbio/hatchet/hatchet/s015/bb/bulk.bb
	diploidbaf: 0.1
	decoding: map
	minK: 2
	maxK: 30
	exactK: 0
	covar: diag
	transmat: diag
	tau: 1e-06
	outsegments: /gpfs/commons/projects/landau_brain_mets/compbio/hatchet/hatchet/s015/bbc/bulk.seg
	outbins: /gpfs/commons/projects/landau_brain_mets/compbio/hatchet/hatchet/s015/bbc/bulk.bbc
	restarts: 10
	subset: None
[2024-Apr-17 21:15:58]# Reading the combined BB file
[2024-Apr-17 21:15:58]# Clustering bins by RD and BAF across tumor samples using locality
[2024-Apr-17 21:48:14]# Checking consistency of results
Traceback (most recent call last):
  File "/gpfs/commons/home/whooper/.conda/envs/hatchet2/bin/hatchet", line 8, in <module>
    sys.exit(main())
  File "/gpfs/commons/home/whooper/.conda/envs/hatchet2/lib/python3.8/site-packages/hatchet/__main__.py", line 61, in main
    globals()[command](args)
  File "/gpfs/commons/home/whooper/.conda/envs/hatchet2/lib/python3.8/site-packages/hatchet/utils/run.py", line 316, in main
    cluster_bins(
  File "/gpfs/commons/home/whooper/.conda/envs/hatchet2/lib/python3.8/site-packages/hatchet/utils/cluster_bins.py", line 71, in main
    assert str(start_row[0]) == my_chr, (start_row[0], my_chr)
AssertionError: ('chr1', "('chr1',)")
```

Do you know what could be causing this? The prior steps proceed without issue. Here's my INI file: 
```
[run]
download_panel=False
genotype_snps=True
count_reads=True
fixed_width=False
count_alleles=True
phase_snps=True
combine_counts=True
cluster_bins=True
loc_clust=True
plot_bins=True
compute_cn=True
plot_cn=True
output=hatchet/s015
reference=GRCh38_full_analysis_set_plus_decoy_hla.cleaned.fasta
normal=s015.normal.bam
bams=s015_01.tumor.bam
samples=s015_01.tumor
processes=4

[genotype_snps]
reference_version=hg38
chr_notation=true
snps=/gpfs/commons/projects/landau_brain_mets/compbio/hatchet/reference-panel/dbsnp_hg38.vcf.gz

[download_panel]
refpaneldir=/gpfs/commons/projects/landau_brain_mets/compbio/hatchet/reference-panel
```

Thanks for your help!
Will

**Comment by willhooper** [comment]
Updating to the latest version solved this, nevermind!
