### ISSUE TITLE
Issue running count-alleles from the demo-complete

### ISSUE THREAD

**Issue by gaitat** [raphael-group/hatchet#228]
I am running `hatchet v2.0.1` with `python v3.12` and trying to run to completion the `demo-complete` with the data provided.
I have downloaded all the files that the demo requires.

I modified the `conda` installation file `pkgs/hatchet-2.0.1-py312h28adbb1_1/lib/python3.12/site-packages/hatchet/utils/run.py`
to include a `--verbose` flag as the first argument to `count_alleles`.

My hatchet.ini file looks like:

	[run]
	genotype_snps=False
	phase_snps=False
	count_alleles=True
	count_reads=False
	combine_counts=False
	cluster_bins=False
	plot_bins=False
	compute_cn=False
	plot_cn=False
	reference=data/hg19.fa
	output=output/
	processes=24
	chromosomes="chr22"
	normal=data/normal.bam
	bams=data/bulk_03clone1_06clone0_01normal.sorted.bam data/bulk_08clone1_Noneclone0_02normal.sorted.bam 	data/bulk_Noneclone1_09clone0_01normal.sorted.bam
	samples=TumorSample1 TumorSample2 TumorSample3
	[genotype_snps]
	snps=.../hatchet/examples/demo-complete/00-All.vcf.gz
	mincov=8
	maxcov=300
	reference_version=hg19
	chr_notation=True
	[count_alleles]
	mincov=8
	maxcov=300
	[combine_counts]
	msr=3000
	mtr=5000

Since I had issues, I decided to run each step separately until I figured out where the problem was.
The demo would not start running until I had specified the `phase_snps` flag and in my case I set it to False.
I have run the step `genotype_snps` successfully.

The next step is the `count_alleles` and that's why it is set to True.
All I get on the terminal is:

	(hatchet) .../hatchet/examples/demo-complete 8623: hatchet run hatchet.ini 
	[2024-Oct-13 09:33:33]# Parsing the input arguments, checking the consistency of given files, and extracting required 	information
	stderr of samtools and bcftools will be collected in the following file "samtools.log"

		normal: ('data/normal.bam', 'normal')
		samples: {('data/bulk_Noneclone1_09clone0_01normal.sorted.bam', 'TumorSample3'), ('data/bulk_03clone1_06clone0_01normal.sorted.bam', 'TumorSample1'), ('data/bulk_08clone1_Noneclone0_02normal.sorted.bam', 'TumorSample2')}
		chromosomes: ['chr22']
		samtools: samtools
		bcftools: bcftools
		snps: {'chr22': 'output/snps/chr22.vcf.gz'}
		reference: data/hg19.fa
		j: 24
		q: 0
		Q: 11
		qual: 11
		E: False
		gamma: 0.05
		maxshift: 0.5
		mincov: 8
		maxcov: 300
		outputNormal: output/baf/normal.1bed
		outputTumors: output/baf/tumor.1bed
		outputSnps: output
		verbose: True
	[2024-Oct-13 09:33:34]# Counting SNPs alleles from the matched-normal sample

The application gets stuck at this point for hours.
Verbose is set to true but I don't get any output.

How much time is required for `demo-complete` to complete?

**Comment by gaitat** [comment]
Update:

Once I followed the instructions in https://github.com/raphael-group/hatchet/issues/227 the above issue was resolved.

Continuing the execution for `demo-complete`, on the step `combine_counts` I encountered the following issue:

    Traceback (most recent call last):
      File ".../miniconda3/envs/hatchet/bin/hatchet", line 11, in <module>
        sys.exit(main())
                 ^^^^^^
      File ".../miniconda3/envs/hatchet/lib/python3.12/site-packages/hatchet/__main__.py", line 61, in main
        globals()[command](args)
      File ".../miniconda3/envs/hatchet/lib/python3.12/site-packages/hatchet/utils/run.py", line 259, in main
        combine_counts(args)
      File ".../miniconda3/envs/hatchet/lib/python3.12/site-packages/hatchet/utils/combine_counts.py", line 110, in main
        big_bb['CORRECTED_READS'] = np.NAN
                                    ^^^^^^
      File ".../miniconda3/envs/hatchet/lib/python3.12/site-packages/numpy/__init__.py", line 414, in __getattr__
        raise AttributeError("module {!r} has no attribute "
    AttributeError: module 'numpy' has no attribute 'NAN'. Did you mean: 'nan'?

I replaced `NAN` with `nan` and got for `cluster_bins`, which I don't know if is correct.

    [2024-Oct-13 12:20:43]# Parsing and checking input arguments

      bbfile: output/bb/bulk.bb
      diploidbaf: 0.1
      decoding: map
      minK: 2
      maxK: 30
      exactK: 0
      covar: diag
      transmat: diag
      tau: 1e-06
      outsegments: output/bbc/bulk.seg
      outbins: output/bbc/bulk.bbc
      restarts: 10
      subset: None
    [2024-Oct-13 12:20:43]# Reading the combined BB file
    [2024-Oct-13 12:20:43]# Clustering bins by RD and BAF across tumor samples using locality
    Model is not converging.  Current: 31297.937522562286 is not greater than 31297.937557373345. Delta is -3.481105886748992e-05
    Model is not converging.  Current: 31297.937522562286 is not greater than 31297.937557373345. Delta is -3.481105886748992e-05
    Model is not converging.  Current: 31297.937522562286 is not greater than 31297.937557373345. Delta is -3.481105886748992e-05
    Model is not converging.  Current: 31297.937522562286 is not greater than 31297.937557373345. Delta is -3.481105886748992e-05
    Model is not converging.  Current: 31297.937522562286 is not greater than 31297.937557373345. Delta is -3.481105886748992e-05
    Model is not converging.  Current: 31297.937522562286 is not greater than 31297.937557373345. Delta is -3.481105886748992e-05
    Model is not converging.  Current: 31297.937522562286 is not greater than 31297.937557373345. Delta is -3.481105886748992e-05
    Model is not converging.  Current: 31297.937522562286 is not greater than 31297.937557373345. Delta is -3.481105886748992e-05
    Model is not converging.  Current: 31297.937522562286 is not greater than 31297.937557373345. Delta is -3.481105886748992e-05
    Model is not converging.  Current: 31297.937522562286 is not greater than 31297.937557373345. Delta is -3.481105886748992e-05
    Model is not converging.  Current: 31725.24687954652 is not greater than 31725.255068392366. Delta is -0.008188845844415482
    Model is not converging.  Current: 31725.246882533058 is not greater than 31725.255111148414. Delta is -0.008228615355619695
    Model is not converging.  Current: 31725.246879864357 is not greater than 31725.255072991105. Delta is -0.008193126748665236
    Model is not converging.  Current: 31725.246881337167 is not greater than 31725.25509411897. Delta is -0.008212781802285463
    Model is not converging.  Current: 31725.246885981134 is not greater than 31725.25515950401. Delta is -0.008273522875242634
    Model is not converging.  Current: 31725.246882430045 is not greater than 31725.255110469552. Delta is -0.008228039507230278
    Model is not converging.  Current: 31725.24687911774 is not greater than 31725.255062229997. Delta is -0.00818311225521029
    Model is not converging.  Current: 31725.246879849605 is not greater than 31725.255072793247. Delta is -0.008192943641915917
    Model is not converging.  Current: 31725.246880037095 is not greater than 31725.255075473702. Delta is -0.008195436606911244
    Model is not converging.  Current: 31725.246880884806 is not greater than 31725.25508765767. Delta is -0.008206772865378298
    Model is not converging.  Current: 31761.481972886246 is not greater than 31761.48342916259. Delta is -0.0014562763426511083
    Model is not converging.  Current: 31761.484990185494 is not greater than 31761.541133626135. Delta is -0.056143440640880726
    Model is not converging.  Current: 31761.482005586957 is not greater than 31761.48391840212. Delta is -0.0019128151616314426
    Model is not converging.  Current: 31761.481958509266 is not greater than 31761.483123859434. Delta is -0.0011653501678665634
    Model is not converging.  Current: 31761.48194020705 is not greater than 31761.482864022953. Delta is -0.000923815903661307
    Model is not converging.  Current: 31761.48193511698 is not greater than 31761.482771498195. Delta is -0.0008363812157767825
    Model is not converging.  Current: 31761.481949777582 is not greater than 31761.48303795272. Delta is -0.001088175136828795
    Model is not converging.  Current: 31761.48367475015 is not greater than 31761.515439987732. Delta is -0.03176523758156691
    Model is not converging.  Current: 31761.49674827259 is not greater than 31761.71832424611. Delta is -0.22157597351906588
    Model is not converging.  Current: 31761.48197946494 is not greater than 31761.483521223963. Delta is -0.0015417590220749844
    Model is not converging.  Current: 31759.317452379648 is not greater than 31759.31745448022. Delta is -2.100572601193562e-06
    Model is not converging.  Current: 31759.31745718718 is not greater than 31759.31753718568. Delta is -7.99985027697403e-05
    Model is not converging.  Current: 31761.152890992264 is not greater than 31761.957949024516. Delta is -0.8050580322524183
    Model is not converging.  Current: 31758.102957722214 is not greater than 31758.599800173866. Delta is -0.4968424516519008
    Model is not converging.  Current: 31764.47509507099 is not greater than 31764.66694389572. Delta is -0.1918488247320056
    Model is not converging.  Current: 31757.817387877592 is not greater than 31758.42990167588. Delta is -0.612513798289001
    Model is not converging.  Current: 31762.37383251214 is not greater than 31763.596419720703. Delta is -1.2225872085618903
    Model is not converging.  Current: 31758.510597957767 is not greater than 31760.68258482736. Delta is -2.17198686959091
    Model is not converging.  Current: 31763.39313180861 is not greater than 31764.315210517496. Delta is -0.9220787088852376
    Model is not converging.  Current: 31789.9884842522 is not greater than 31792.455809448402. Delta is -2.4673251962012728
    Model is not converging.  Current: 31762.337315655514 is not greater than 31762.601747087396. Delta is -0.26443143188225804
    Model is not converging.  Current: 31757.310952263088 is not greater than 31759.14828980646. Delta is -1.8373375433729962
    Model is not converging.  Current: 31789.87284527547 is not greater than 31792.402392422817. Delta is -2.52954714734733
    Model is not converging.  Current: 31757.784392200025 is not greater than 31759.730758292273. Delta is -1.946366092248354
    Model is not converging.  Current: 31760.27439869989 is not greater than 31761.511612948198. Delta is -1.237214248307282
    Model is not converging.  Current: 31760.45872079159 is not greater than 31760.622578867224. Delta is -0.16385807563347043
    Model is not converging.  Current: 31763.170631339923 is not greater than 31764.177569055024. Delta is -1.0069377151012304
    Model is not converging.  Current: 31762.709638777407 is not greater than 31762.893845272483. Delta is -0.18420649507606868
    Model is not converging.  Current: 31772.67991249331 is not greater than 31776.988477755982. Delta is -4.308565262672346
    Model is not converging.  Current: 31759.674638296397 is not greater than 31760.48824815407. Delta is -0.813609857672418
    Model is not converging.  Current: 31761.719662850188 is not greater than 31762.540213277007. Delta is -0.8205504268189543
    Model is not converging.  Current: 31758.58383567794 is not greater than 31759.762779472625. Delta is -1.1789437946863472
    Model is not converging.  Current: 31759.058351063642 is not greater than 31760.047715305984. Delta is -0.989364242341253
    Model is not converging.  Current: 31757.785729700416 is not greater than 31758.246219589506. Delta is -0.46048988909024047
    Model is not converging.  Current: 31778.464918100723 is not greater than 31780.772291673984. Delta is -2.3073735732614296
    Model is not converging.  Current: 31787.900378557737 is not greater than 31789.062263752938. Delta is -1.161885195200739
    Model is not converging.  Current: 31770.48813424164 is not greater than 31773.730864519854. Delta is -3.242730278212548
    Model is not converging.  Current: 31759.547105116202 is not greater than 31760.597328430318. Delta is -1.0502233141160104
    Model is not converging.  Current: 31760.679856842282 is not greater than 31760.941333374947. Delta is -0.26147653266525595
    Model is not converging.  Current: 31752.914641106996 is not greater than 31755.303642919876. Delta is -2.3890018128804513
    Model is not converging.  Current: 31771.028267391684 is not greater than 31776.03354227135. Delta is -5.0052748796661035
    Model is not converging.  Current: 31775.257178217515 is not greater than 31778.328420503753. Delta is -3.0712422862379753
    Model is not converging.  Current: 31771.00791533711 is not greater than 31775.152691834788. Delta is -4.144776497676503
    Model is not converging.  Current: 31784.201229428512 is not greater than 31785.831706450095. Delta is -1.6304770215829194
    Model is not converging.  Current: 31758.840161623717 is not greater than 31758.992967881903. Delta is -0.15280625818559201
    Model is not converging.  Current: 31785.952598927073 is not greater than 31788.43387234153. Delta is -2.4812734144579736
    Model is not converging.  Current: 31766.537071566538 is not greater than 31771.439608017365. Delta is -4.902536450827029
    Model is not converging.  Current: 31783.4970307845 is not greater than 31786.311298622764. Delta is -2.814267838264641
    Model is not converging.  Current: 31784.91461702648 is not greater than 31787.31512003641. Delta is -2.400503009928798
    Model is not converging.  Current: 31758.330933851765 is not greater than 31758.632076478094. Delta is -0.30114262632923783
    Model is not converging.  Current: 31756.25456441668 is not greater than 31756.6642817745. Delta is -0.4097173578229558
    Model is not converging.  Current: 31784.51208659241 is not greater than 31787.0798048789. Delta is -2.567718286489253
    Model is not converging.  Current: 31757.534333405765 is not greater than 31758.95249667878. Delta is -1.4181632730142155
    Model is not converging.  Current: 31756.860530333994 is not greater than 31757.35947388555. Delta is -0.49894355155629455
    Model is not converging.  Current: 31758.56123391307 is not greater than 31761.410516039265. Delta is -2.8492821261934296
    Model is not converging.  Current: 31784.811530706935 is not greater than 31785.33990282986. Delta is -0.5283721229243383
    Model is not converging.  Current: 31768.551488692858 is not greater than 31772.552552907993. Delta is -4.001064215135557
    Model is not converging.  Current: 31784.402638512573 is not greater than 31786.113013077087. Delta is -1.7103745645144954
    Model is not converging.  Current: 31759.247704901452 is not greater than 31761.85313817376. Delta is -2.605433272306982
    Model is not converging.  Current: 31756.649087368798 is not greater than 31756.94549848145. Delta is -0.29641111265300424
    Model is not converging.  Current: 31760.256694776657 is not greater than 31762.870163638683. Delta is -2.613468862025911
    Model is not converging.  Current: 31750.501742685923 is not greater than 31751.040465317954. Delta is -0.53872263203084
    Model is not converging.  Current: 31781.80916863119 is not greater than 31783.365953594206. Delta is -1.5567849630169803
    Model is not converging.  Current: 31775.054510230708 is not greater than 31776.790621253935. Delta is -1.7361110232268402
    Model is not converging.  Current: 31765.721186562838 is not greater than 31770.528804946505. Delta is -4.807618383667432
    Model is not converging.  Current: 31755.345635524067 is not greater than 31755.35556546568. Delta is -0.009929941614245763
    Model is not converging.  Current: 31785.233749318148 is not greater than 31788.557165605966. Delta is -3.323416287817963
    Model is not converging.  Current: 31751.445866484788 is not greater than 31753.853886573328. Delta is -2.40802008854007
    Model is not converging.  Current: 31780.42067910721 is not greater than 31783.68262186984. Delta is -3.261942762630497
    Model is not converging.  Current: 31752.27110235968 is not greater than 31752.3022455083. Delta is -0.03114314862250467
    Model is not converging.  Current: 31757.584623637536 is not greater than 31761.330708055026. Delta is -3.746084417489328
    Model is not converging.  Current: 31779.83198927053 is not greater than 31781.15994642384. Delta is -1.3279571533093986
    Model is not converging.  Current: 31751.189275727953 is not greater than 31752.62421023431. Delta is -1.4349345063565124
    Model is not converging.  Current: 31753.940397965474 is not greater than 31754.336174591586. Delta is -0.39577662611191045
    Model is not converging.  Current: 31779.88187649966 is not greater than 31780.322329070008. Delta is -0.44045257034667884
    Model is not converging.  Current: 31781.320094061713 is not greater than 31783.294299174966. Delta is -1.9742051132525376
    Model is not converging.  Current: 31753.53680679519 is not greater than 31754.617531562228. Delta is -1.0807247670381912
    Model is not converging.  Current: 31756.349927217794 is not greater than 31757.790737246432. Delta is -1.440810028638225
    Model is not converging.  Current: 31756.682463391175 is not greater than 31758.669133503427. Delta is -1.9866701122518862
    Model is not converging.  Current: 31748.33697664474 is not greater than 31749.599441765575. Delta is -1.2624651208352589
    Model is not converging.  Current: 31752.663277612923 is not greater than 31753.354869888088. Delta is -0.6915922751650214
    Model is not converging.  Current: 31778.581690085746 is not greater than 31780.481403234746. Delta is -1.8997131489995809
    Model is not converging.  Current: 31748.595560262045 is not greater than 31751.11016677771. Delta is -2.514606515665946
    Model is not converging.  Current: 31752.33475178684 is not greater than 31752.909250384033. Delta is -0.5744985971941787
    Model is not converging.  Current: 31750.178702018504 is not greater than 31752.360005087474. Delta is -2.18130306897001
    Model is not converging.  Current: 31752.510207661853 is not greater than 31753.28784907103. Delta is -0.7776414091786137
    Model is not converging.  Current: 31758.798780103232 is not greater than 31762.79360263055. Delta is -3.9948225273183198
    Model is not converging.  Current: 31755.222967717586 is not greater than 31758.33718209426. Delta is -3.1142143766737718
    Model is not converging.  Current: 31750.23508153984 is not greater than 31750.822513005696. Delta is -0.5874314658576623
    Model is not converging.  Current: 31777.43627616984 is not greater than 31779.249203788102. Delta is -1.81292761826262
    Model is not converging.  Current: 31747.46101905311 is not greater than 31749.28074061708. Delta is -1.8197215639702335
    Model is not converging.  Current: 31750.605965841907 is not greater than 31751.046063501508. Delta is -0.440097659600724
    Model is not converging.  Current: 31776.877390909158 is not greater than 31777.298826581373. Delta is -0.42143567221501144
    Model is not converging.  Current: 31750.520448650124 is not greater than 31751.19115972704. Delta is -0.670711076916632
    Model is not converging.  Current: 31776.659690126016 is not greater than 31778.138182040555. Delta is -1.4784919145386084
    Model is not converging.  Current: 31750.34787851755 is not greater than 31750.724814911042. Delta is -0.37693639349163277
    Model is not converging.  Current: 31753.98278259283 is not greater than 31754.175432567074. Delta is -0.19264997424397734
    Model is not converging.  Current: 31752.290469595486 is not greater than 31752.3573089104. Delta is -0.06683931491352268
    Model is not converging.  Current: 31776.21284935087 is not greater than 31777.289102353127. Delta is -1.0762530022548162
    Model is not converging.  Current: 31750.26156678444 is not greater than 31751.54724648201. Delta is -1.285679697568412
    Model is not converging.  Current: 31775.35332280138 is not greater than 31776.678247965567. Delta is -1.3249251641864248
    Model is not converging.  Current: 31745.924884018514 is not greater than 31747.148700933612. Delta is -1.2238169150987233
    Model is not converging.  Current: 31751.099750646776 is not greater than 31751.127855432456. Delta is -0.028104785680625355
    Model is not converging.  Current: 31748.810775552 is not greater than 31749.44265655493. Delta is -0.631881002929731
    Model is not converging.  Current: 31768.97626872662 is not greater than 31769.808853868617. Delta is -0.8325851419976971
    Model is not converging.  Current: 31746.816949900072 is not greater than 31748.999380690824. Delta is -2.1824307907518232
    Model is not converging.  Current: 31775.588651382 is not greater than 31776.043450861565. Delta is -0.45479947956482647
    Model is not converging.  Current: 31745.287678973415 is not greater than 31745.953160875444. Delta is -0.665481902029569
    Model is not converging.  Current: 31774.65289424031 is not greater than 31776.468933105964. Delta is -1.8160388656542636
    Model is not converging.  Current: 31753.220810290724 is not greater than 31756.22675773039. Delta is -3.0059474396657606
    Model is not converging.  Current: 31777.61165823203 is not greater than 31777.646489393257. Delta is -0.03483116122879437
    Model is not converging.  Current: 31749.687814485336 is not greater than 31750.297088534557. Delta is -0.609274049220403
    Model is not converging.  Current: 31776.315474345334 is not greater than 31777.373562617933. Delta is -1.0580882725989795
    Model is not converging.  Current: 31773.023809442362 is not greater than 31774.7096451592. Delta is -1.6858357168384828
    Model is not converging.  Current: 31774.517295106918 is not greater than 31777.515762475978. Delta is -2.9984673690596537
    Model is not converging.  Current: 31775.113177470455 is not greater than 31776.34309402512. Delta is -1.229916554664669
    Model is not converging.  Current: 31751.924645418236 is not greater than 31754.481125959628. Delta is -2.556480541392375
    Model is not converging.  Current: 31749.725220020515 is not greater than 31752.14259247817. Delta is -2.4173724576539826
    Model is not converging.  Current: 31774.500133190308 is not greater than 31777.13961916093. Delta is -2.6394859706233547
    Model is not converging.  Current: 31745.445904586428 is not greater than 31746.92730911318. Delta is -1.4814045267521578
    Model is not converging.  Current: 31748.68605128072 is not greater than 31749.24813084975. Delta is -0.5620795690301748
    Model is not converging.  Current: 31746.623392133348 is not greater than 31747.283352489998. Delta is -0.6599603566501173
    Model is not converging.  Current: 31745.32550566252 is not greater than 31745.325556317242. Delta is -5.065472214482725e-05
    Model is not converging.  Current: 31745.471006468742 is not greater than 31745.630178321524. Delta is -0.15917185278158286
    Model is not converging.  Current: 31748.005222668286 is not greater than 31748.554251195583. Delta is -0.549028527297196
    Model is not converging.  Current: 31773.269016612605 is not greater than 31774.871266300983. Delta is -1.602249688377924
    Model is not converging.  Current: 31751.05093109867 is not greater than 31754.870476462907. Delta is -3.8195453642365464
    Model is not converging.  Current: 31748.23804666384 is not greater than 31748.902285552886. Delta is -0.6642388890468283
    Model is not converging.  Current: 31747.871846385493 is not greater than 31748.108527406366. Delta is -0.2366810208732204
    Model is not converging.  Current: 31743.94721283599 is not greater than 31745.264866910366. Delta is -1.3176540743770602
    Model is not converging.  Current: 31748.40509621892 is not greater than 31748.914909985713. Delta is -0.5098137667919218
    Model is not converging.  Current: 31771.849456765518 is not greater than 31773.503935811084. Delta is -1.6544790455664042
    Model is not converging.  Current: 31745.6975144408 is not greater than 31746.3121344765. Delta is -0.6146200356997724
    Model is not converging.  Current: 31748.705255654946 is not greater than 31748.7503524839. Delta is -0.045096828955138335
    Model is not converging.  Current: 31748.36373115413 is not greater than 31748.440054889546. Delta is -0.07632373541491688
    Model is not converging.  Current: 31748.050419302737 is not greater than 31748.588387173477. Delta is -0.5379678707395215
    Model is not converging.  Current: 31770.81421914555 is not greater than 31771.309814747405. Delta is -0.49559560185298324
    Model is not converging.  Current: 31774.38630430277 is not greater than 31776.016407398998. Delta is -1.6301030962276855
    Model is not converging.  Current: 31743.92114783632 is not greater than 31743.921855566692. Delta is -0.0007077303707774263
    Model is not converging.  Current: 31747.650108949914 is not greater than 31747.98237737712. Delta is -0.33226842720614513
    Model is not converging.  Current: 31757.336580399056 is not greater than 31763.5808546907. Delta is -6.244274291642796
    Model is not converging.  Current: 31773.305662666608 is not greater than 31775.72966033861. Delta is -2.4239976720018603
    Model is not converging.  Current: 31748.90454374113 is not greater than 31751.975903069644. Delta is -3.071359328514518
    Model is not converging.  Current: 31770.90253367993 is not greater than 31772.074944323438. Delta is -1.172410643506737
    Model is not converging.  Current: 31774.72180997321 is not greater than 31774.85951703115. Delta is -0.13770705794013338
    Model is not converging.  Current: 31746.748981880002 is not greater than 31747.586869019375. Delta is -0.8378871393724694
    Model is not converging.  Current: 31745.443453003994 is not greater than 31745.766791353883. Delta is -0.32333834988821764
    Model is not converging.  Current: 31755.11979068959 is not greater than 31758.8575702962. Delta is -3.7377796066102746
    Model is not converging.  Current: 31772.102401749762 is not greater than 31773.70050842226. Delta is -1.5981066724962147
    Model is not converging.  Current: 31745.074715712737 is not greater than 31745.154161836665. Delta is -0.0794461239274824
    Model is not converging.  Current: 31773.195244550116 is not greater than 31774.474337161948. Delta is -1.2790926118323114
    Model is not converging.  Current: 31744.840378295634 is not greater than 31746.14719854119. Delta is -1.3068202455579012
    Model is not converging.  Current: 31742.117191781406 is not greater than 31743.32103060702. Delta is -1.2038388256150938
    Model is not converging.  Current: 31771.615512350218 is not greater than 31772.931480881853. Delta is -1.3159685316350078
    Model is not converging.  Current: 31770.3119462761 is not greater than 31771.90832541265. Delta is -1.5963791365502402
    Model is not converging.  Current: 31770.486173850484 is not greater than 31771.636735439304. Delta is -1.1505615888199827
    Model is not converging.  Current: 31746.788635425713 is not greater than 31747.356464969467. Delta is -0.5678295437537599
    Model is not converging.  Current: 31771.557811693616 is not greater than 31773.88349699343. Delta is -2.3256852998129034
    Model is not converging.  Current: 31744.77570227532 is not greater than 31745.56018953069. Delta is -0.784487255368731
    Model is not converging.  Current: 31744.582757284243 is not greater than 31745.45961572672. Delta is -0.8768584424760775
    Model is not converging.  Current: 31745.86324415385 is not greater than 31746.255542114708. Delta is -0.39229796085783164
    Model is not converging.  Current: 31743.968880471904 is not greater than 31744.373697761253. Delta is -0.40481728934901184
    Model is not converging.  Current: 31749.554857563504 is not greater than 31753.57974807799. Delta is -4.024890514487197
    Model is not converging.  Current: 31768.423092016044 is not greater than 31770.342344757966. Delta is -1.9192527419218095
    Model is not converging.  Current: 31772.924753151867 is not greater than 31773.099306881028. Delta is -0.17455372916083434
    Model is not converging.  Current: 31745.06759031907 is not greater than 31745.475880605023. Delta is -0.40829028595180716
    Model is not converging.  Current: 31743.393350383718 is not greater than 31743.574267919426. Delta is -0.1809175357084314
    Model is not converging.  Current: 31765.51383364352 is not greater than 31766.69664180687. Delta is -1.1828081633502734
    Model is not converging.  Current: 31746.719789397666 is not greater than 31749.18415023472. Delta is -2.464360837053391
    Model is not converging.  Current: 31770.768348925994 is not greater than 31772.539915446632. Delta is -1.7715665206378617
    Model is not converging.  Current: 31744.85034241056 is not greater than 31745.050560937474. Delta is -0.2002185269157053
    Model is not converging.  Current: 31742.58424031658 is not greater than 31743.700694625513. Delta is -1.116454308932589
    Model is not converging.  Current: 31741.537586470786 is not greater than 31743.378347169997. Delta is -1.840760699211387
    Model is not converging.  Current: 31744.740481833203 is not greater than 31749.665760966807. Delta is -4.925279133603908
    Model is not converging.  Current: 31743.966563916205 is not greater than 31744.291677725723. Delta is -0.32511380951837054
    Model is not converging.  Current: 31758.057648416765 is not greater than 31760.78477953149. Delta is -2.7271311147233064
    Model is not converging.  Current: 31768.88988775226 is not greater than 31770.10565736787. Delta is -1.2157696156100428
    Model is not converging.  Current: 31740.716979972814 is not greater than 31741.432862300233. Delta is -0.7158823274185124
    Model is not converging.  Current: 31754.326597092626 is not greater than 31758.136586116347. Delta is -3.8099890237208456
    Model is not converging.  Current: 31744.77864950298 is not greater than 31747.11545062181. Delta is -2.336801118832227
    Model is not converging.  Current: 31770.56150857066 is not greater than 31771.507591598565. Delta is -0.9460830279058428
    Model is not converging.  Current: 31747.996219018263 is not greater than 31752.27719564772. Delta is -4.280976629455836
    Model is not converging.  Current: 31755.3618778568 is not greater than 31756.978851444142. Delta is -1.6169735873409081
    Model is not converging.  Current: 31769.820963473438 is not greater than 31770.75760849127. Delta is -0.9366450178313244
    Model is not converging.  Current: 31742.726147602105 is not greater than 31744.48264981935. Delta is -1.7565022172457248
    Model is not converging.  Current: 31746.80739805803 is not greater than 31750.90989183503. Delta is -4.102493776998017
    Model is not converging.  Current: 31742.962423566 is not greater than 31743.641471415216. Delta is -0.6790478492148395
    Model is not converging.  Current: 31769.146671316455 is not greater than 31771.150617028135. Delta is -2.0039457116799895
    Model is not converging.  Current: 31735.668288606947 is not greater than 31737.918406809917. Delta is -2.250118202970043
    Model is not converging.  Current: 31756.094489682084 is not greater than 31757.920271737377. Delta is -1.82578205529353
    Model is not converging.  Current: 31741.66155128847 is not greater than 31743.959162167936. Delta is -2.297610879464628
    Model is not converging.  Current: 31739.58950951995 is not greater than 31741.46655115334. Delta is -1.8770416333900357
    Model is not converging.  Current: 31742.85522202648 is not greater than 31743.262447359215. Delta is -0.40722533273583394
    Model is not converging.  Current: 31754.606300933447 is not greater than 31756.937193547372. Delta is -2.3308926139252435
    Model is not converging.  Current: 31739.06585477881 is not greater than 31740.406678702715. Delta is -1.340823923903372
    Model is not converging.  Current: 31745.779426023044 is not greater than 31750.491596618867. Delta is -4.712170595823409
    Model is not converging.  Current: 31741.677214689713 is not greater than 31742.41532097594. Delta is -0.7381062862259569
    Model is not converging.  Current: 31764.945127755254 is not greater than 31765.80098960657. Delta is -0.8558618513161491
    Model is not converging.  Current: 31741.83512219377 is not greater than 31742.597374728128. Delta is -0.7622525343576854
    Model is not converging.  Current: 31743.808135333704 is not greater than 31745.662540834397. Delta is -1.8544055006932467
    Model is not converging.  Current: 31741.383091456326 is not greater than 31742.786418276664. Delta is -1.4033268203384068
    Model is not converging.  Current: 31765.773686445074 is not greater than 31765.861406852327. Delta is -0.08772040725307306
    Model is not converging.  Current: 31746.85957561562 is not greater than 31749.21440359855. Delta is -2.3548279829301464
    Model is not converging.  Current: 31768.141577035352 is not greater than 31770.16328473994. Delta is -2.021707704589062
    Model is not converging.  Current: 31741.872418832005 is not greater than 31742.227969842595. Delta is -0.35555101059071603
    Model is not converging.  Current: 31766.79867339416 is not greater than 31769.206166937543. Delta is -2.407493543381861
    Model is not converging.  Current: 31766.578638418443 is not greater than 31768.259965259906. Delta is -1.6813268414625782
    Model is not converging.  Current: 31746.773708965917 is not greater than 31748.084774003953. Delta is -1.3110650380367588
    Model is not converging.  Current: 31746.03825448443 is not greater than 31749.581642892197. Delta is -3.5433884077683615
    Model is not converging.  Current: 31741.790636708585 is not greater than 31742.25538615382. Delta is -0.46474944523652084
    Model is not converging.  Current: 31743.63040792089 is not greater than 31746.223668189923. Delta is -2.5932602690336353
    Model is not converging.  Current: 31740.999272785943 is not greater than 31741.107336242694. Delta is -0.10806345675155171
    Model is not converging.  Current: 31741.47474911824 is not greater than 31741.83310832306. Delta is -0.3583592048198625
    Model is not converging.  Current: 31754.39677652464 is not greater than 31757.945651789993. Delta is -3.5488752653509437
    Model is not converging.  Current: 31741.04790698878 is not greater than 31741.937576249937. Delta is -0.8896692611560866
    Model is not converging.  Current: 31739.73156423532 is not greater than 31740.313513624013. Delta is -0.58194938869201
    Model is not converging.  Current: 31740.812499833643 is not greater than 31741.511609334873. Delta is -0.6991095012308506
    Model is not converging.  Current: 31767.236891290504 is not greater than 31768.816883034204. Delta is -1.579991743699793
    Model is not converging.  Current: 31742.78639005652 is not greater than 31743.550161062783. Delta is -0.7637710062626866
    Model is not converging.  Current: 31762.243799836782 is not greater than 31762.84799570386. Delta is -0.6041958670793974
    Model is not converging.  Current: 31766.496078806955 is not greater than 31768.201357203383. Delta is -1.7052783964281844
    Model is not converging.  Current: 31740.51858182407 is not greater than 31741.035138338328. Delta is -0.5165565142560808
    Model is not converging.  Current: 31765.93850945313 is not greater than 31766.909393333255. Delta is -0.9708838801234378
    Model is not converging.  Current: 31738.787276436775 is not greater than 31739.17039803797. Delta is -0.38312160119676264
    [2024-Oct-13 12:21:51]# Checking consistency of results
    [2024-Oct-13 12:21:51]# Writing output
    [2024-Oct-13 12:21:51]# Done

**Comment by simozacca** [comment]
Thank you for highlighting this issue; this is also a recent bug due to the new version of numpy. Please follow the issue and find a temporary solution in #229
