### ISSUE TITLE
deBAF error

### ISSUE THREAD

**Issue by kristianunger** [raphael-group/hatchet#48]
Hi!

When doing the preprocessing steps I experience an error in the deBAF step.

I was running the following

`#BIN

python -m hatchet binBAM -N ${NORMAL} -T ${BAMS} -S ${ALLNAMES} \
-b 200kb -g ${REF} -j ${J} \
-q 20 -O ${BIN}normal.1bed -o ${BIN}bulk.1bed -v &> ${BIN}bins.log

#deBAF

python -m hatchet  deBAF -N ${NORMAL} -T ${BAMS} -S ${ALLNAMES} \
-r ${REF} -j ${J} -q 20 -Q 20 -U 20 -c 4 \
-C 300 -O ${BAF}normal.1bed -o ${BAF}bulk.1bed -v \
-bt $BCF -st $BCF -L $SNPSTAB \
&> ${BAF}bafs.log`

###
the log gives me the following:

2021-Mar-17 23:15:04]# Counting SNPs alleles from the matched-normal sample
[2021-Mar-17 23:15:05]AlleleCounter-1 starts on LMU01_NG for chr1
[2021-Mar-17 23:15:05]AlleleCounter-2 starts on LMU01_NG for chr2
[2021-Mar-17 23:15:05]AlleleCounter-3 starts on LMU01_NG for chr3
[2021-Mar-17 23:15:05]AlleleCounter-4 starts on LMU01_NG for chr4
[2021-Mar-17 23:15:05]AlleleCounter-5 starts on LMU01_NG for chr5
[2021-Mar-17 23:15:05]AlleleCounter-6 starts on LMU01_NG for chr6
[2021-Mar-17 23:15:05]AlleleCounter-7 starts on LMU01_NG for chr7
[2021-Mar-17 23:15:05]AlleleCounter-8 starts on LMU01_NG for chr8
[2021-Mar-17 23:15:05]AlleleCounter-9 starts on LMU01_NG for chr9
[2021-Mar-17 23:15:05]AlleleCounter-10 starts on LMU01_NG for chr10
[2021-Mar-17 23:15:05]AlleleCounter-11 starts on LMU01_NG for chr11
[2021-Mar-17 23:15:05]AlleleCounter-12 starts on LMU01_NG for chr12
[2021-Mar-17 23:15:05]AlleleCounter-13 starts on LMU01_NG for chr13
[2021-Mar-17 23:15:05]AlleleCounter-14 starts on LMU01_NG for chr14
[2021-Mar-17 23:15:05]AlleleCounter-15 starts on LMU01_NG for chr15
[2021-Mar-17 23:15:05]AlleleCounter-16 starts on LMU01_NG for chr16
[2021-Mar-17 23:15:05]AlleleCounter-17 starts on LMU01_NG for chr17
[2021-Mar-17 23:15:05]AlleleCounter-18 starts on LMU01_NG for chr18
[2021-Mar-17 23:15:05]AlleleCounter-19 starts on LMU01_NG for chr19
[2021-Mar-17 23:15:05]AlleleCounter-20 starts on LMU01_NG for chr20
[2021-Mar-17 23:15:05]AlleleCounter-21 starts on LMU01_NG for chr21
[2021-Mar-17 23:15:05]AlleleCounter-22 starts on LMU01_NG for chr22
Progress: |----------------------------------------| 0.0% CompleteProcess AlleleCounter-19:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr19 of LMU01_NG, please check errors in ./LMU01_NG_chr19_bcftools.log!
Process AlleleCounter-18:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr18 of LMU01_NG, please check errors in ./LMU01_NG_chr18_bcftools.log!
Process AlleleCounter-22:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr22 of LMU01_NG, please check errors in ./LMU01_NG_chr22_bcftools.log!
Process AlleleCounter-2:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr2 of LMU01_NG, please check errors in ./LMU01_NG_chr2_bcftools.log!
Process AlleleCounter-10:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr10 of LMU01_NG, please check errors in ./LMU01_NG_chr10_bcftools.log!
Process AlleleCounter-20:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr20 of LMU01_NG, please check errors in ./LMU01_NG_chr20_bcftools.log!
Process AlleleCounter-17:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr17 of LMU01_NG, please check errors in ./LMU01_NG_chr17_bcftools.log!
Process AlleleCounter-9:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr9 of LMU01_NG, please check errors in ./LMU01_NG_chr9_bcftools.log!
Process AlleleCounter-15:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr15 of LMU01_NG, please check errors in ./LMU01_NG_chr15_bcftools.log!
Process AlleleCounter-3:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr3 of LMU01_NG, please check errors in ./LMU01_NG_chr3_bcftools.log!
Process AlleleCounter-13:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr13 of LMU01_NG, please check errors in ./LMU01_NG_chr13_bcftools.log!
Process AlleleCounter-5:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr5 of LMU01_NG, please check errors in ./LMU01_NG_chr5_bcftools.log!
Process AlleleCounter-11:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr11 of LMU01_NG, please check errors in ./LMU01_NG_chr11_bcftools.log!
Process AlleleCounter-21:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr21 of LMU01_NG, please check errors in ./LMU01_NG_chr21_bcftools.log!
Process AlleleCounter-12:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr12 of LMU01_NG, please check errors in ./LMU01_NG_chr12_bcftools.log!
Process AlleleCounter-8:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr8 of LMU01_NG, please check errors in ./LMU01_NG_chr8_bcftools.log!
Process AlleleCounter-14:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr14 of LMU01_NG, please check errors in ./LMU01_NG_chr14_bcftools.log!
Process AlleleCounter-1:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr1 of LMU01_NG, please check errors in ./LMU01_NG_chr1_bcftools.log!
Process AlleleCounter-6:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr6 of LMU01_NG, please check errors in ./LMU01_NG_chr6_bcftools.log!
Process AlleleCounter-7:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr7 of LMU01_NG, please check errors in ./LMU01_NG_chr7_bcftools.log!
Process AlleleCounter-16:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr16 of LMU01_NG, please check errors in ./LMU01_NG_chr16_bcftools.log!
Process AlleleCounter-4:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 179, in run
    snps = self.countAlleles(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 198, in countAlleles
    raise ValueError(sp.error('Allele counting failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: Allele counting failed on chr4 of LMU01_NG, please check errors in ./LMU01_NG_chr4_bcftools.log!
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/__main__.py", line 45, in <module>
    globals()[command](args)
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 25, in main
    snps = counting(bcftools=args["bcftools"], reference=args["reference"], samples=[args["normal"]], chromosomes=args["chromosomes"], num_workers=args["j"],
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/utils/deBAF.py", line 131, in counting
    tasks.join()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/queues.py", line 326, in join
    self._cond.wait()
  File "/home/zyto/unger/anaconda3/envs/hatchet/lib/python3.8/multiprocessing/synchronize.py", line 261, in wait
    return self._wait_semaphore.acquire(True, timeout)

bcftools.log gives me:

[E::hts_open_format] Failed to open file "[]" : No such file or directory
bcftools mpileup: Could not read file "[]"Failed to read from standard input: unknown file type

###
as input I used the mapped bams of a normal tissue and of primary and relapse of the the patient. For the SNP list I imported Homo_sapiens_assembly38.dbsnp138.vcf from the GATK repository into R using vcfR and wrote a tab-delimited text file with two columns (chromosome and position) without header.

Any suggestions what might cause these errors?

**Comment by simozacca** [comment]
The new version of HATCHet includes a new step called `SNPCalling` and it has a slightly different structure. We are working on updating the documentation and in the meanwhile could you please check out the complete demo available at:

[complete demo](https://github.com/raphael-group/hatchet/blob/master/examples/demo-complete/demo-complete.sh)

**Comment by kristianunger** [comment]
> The new version of HATCHet includes a new step called `SNPCalling` and it has a slightly different structure. We are working on updating the documentation and in the meanwhile could you please check out the complete demo available at:
> 
> [complete demo](https://github.com/raphael-group/hatchet/blob/master/examples/demo-complete/demo-complete.sh)

Started with the demo. Downloaded the files and now execute runUnphased.sh. 

In the SNPcaller-step I get a couple of errors all like this:

`Process Caller-5:
Traceback (most recent call last):
  File "/home/zyto/unger/anaconda3/envs/Hatchet/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/zyto/unger/anaconda3/envs/Hatchet/lib/python3.7/site-packages/hatchet/utils/SNPCaller.py", line 121, in run
    snps = self.callSNPs(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2])
  File "/home/zyto/unger/anaconda3/envs/Hatchet/lib/python3.7/site-packages/hatchet/utils/SNPCaller.py", line 138, in callSNPs
    raise ValueError(sp.error('SNP Calling failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname))
ValueError: SNP Calling failed on chr5 of Normal, please check errors in /home/zyto/unger/WES_Rezidiv_HNSCC_Clonality/Hatchet/hatchet/examples/demo-complete/snps/Normal_chr5_bcftools.log!`

Here the Normal_chr5_bcftools.log:

`E::bgzf_read] Read block operation failed with error 4 after 44546 of 56208 bytes
Failed to open https://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh37p13/VCF/GATK/00-All.vcf.gz: could not load index`

Any suggestion?

**Comment by kristianunger** [comment]
> > The new version of HATCHet includes a new step called `SNPCalling` and it has a slightly different structure. We are working on updating the documentation and in the meanwhile could you please check out the complete demo available at:
> > [complete demo](https://github.com/raphael-group/hatchet/blob/master/examples/demo-complete/demo-complete.sh)
> 
> Started with the demo. Downloaded the files and now execute runUnphased.sh.
> 
> In the SNPcaller-step I get a couple of errors all like this:
> 
> `Process Caller-5: Traceback (most recent call last): File "/home/zyto/unger/anaconda3/envs/Hatchet/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap self.run() File "/home/zyto/unger/anaconda3/envs/Hatchet/lib/python3.7/site-packages/hatchet/utils/SNPCaller.py", line 121, in run snps = self.callSNPs(bamfile=next_task[0], samplename=next_task[1], chromosome=next_task[2]) File "/home/zyto/unger/anaconda3/envs/Hatchet/lib/python3.7/site-packages/hatchet/utils/SNPCaller.py", line 138, in callSNPs raise ValueError(sp.error('SNP Calling failed on {} of {}, please check errors in {}!').format(chromosome, samplename, errname)) ValueError: SNP Calling failed on chr5 of Normal, please check errors in /home/zyto/unger/WES_Rezidiv_HNSCC_Clonality/Hatchet/hatchet/examples/demo-complete/snps/Normal_chr5_bcftools.log!`
> 
> Here the Normal_chr5_bcftools.log:
> 
> `E::bgzf_read] Read block operation failed with error 4 after 44546 of 56208 bytes Failed to open https://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh37p13/VCF/GATK/00-All.vcf.gz: could not load index`
> 
> Any suggestion?

Manually downloading did the trick...

**Comment by simozacca** [comment]
@brian-arnold please close the issue after updating the documentation with downloading and local usage instructions

**Comment by brian-arnold** [comment]
The config.sh file now allows users to specify the LIST variable, directing HATCHet to use a locally stored VCF of known germline SNP positions instead of HATCHet automatically downloading one from the internet. If LIST is left blank ("") in the config.sh file, then HATCHet attempts to download a list of SNP positions based on the reference genome version and chromosome annotation (which are specified by REF_VERS and CHR_NOTATION in config.sh).
