### ISSUE TITLE
clubb error 

### ISSUE THREAD

**Issue by jennyp76** [raphael-group/hatchet#50]
Hi, 
Thanks for the wonderful tool.
I am handling WES multi-region samples (4~5 samples per patient including 1 normal sample). Average coverage is X180. I got an error below while running the script below that. 

**[error]**
12:14:20]'python3 -m hatchet cluBB bb/bulk.bb -o bbc/bulk.seg -O bbc/bulk.bbc -e 11150 -d 0.1 -tR 0.15 -tB 0.04 -u 20 -dR 0.002 -dB 0.002
ESC[1mESC[95m[2021-Apr-06 12:14:22]# Parsing and checking input arguments
ESC[0mESC[1mESC[95m[2021-Apr-06 12:14:22]# Reading the combined BB file
ESC[0mESC[1mESC[95m[2021-Apr-06 12:14:22]# Format data to cluster
ESC[0mESC[1mESC[95m[2021-Apr-06 12:14:22]# Bootstrap each bin for clustering
ESC[0mESC[1mESC[95m[2021-Apr-06 12:14:24]# Clustering bins by RD and BAF across tumor samples
ESC[0mESC[92m[2021-Apr-06 12:14:25]## Clustering with K=50 and c=0.02...
ESC[0mESC[1mESC[95m[2021-Apr-06 18:44:38]# Refining clustering using given tolerances
ESC[0mTraceback (most recent call last):
  File "/opt/Yonsei/python/3.8.1/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/Yonsei/python/3.8.1/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/Yonsei/python/3.8.1/lib/python3.8/site-packages/hatchet/__main__.py", line 45, in <module>
    globals()[command](args)
  File "/opt/Yonsei/python/3.8.1/lib/python3.8/site-packages/hatchet/utils/cluBB.py", line 34, in main
    clusterAssignments, numClusters = refineClustering(combo=combo, assign=clusterAssignments, assignidx=bintoidx, samples=samples, rdtol=args['rdtol'], baftol=a
rgs['baftol'])
  File "/opt/Yonsei/python/3.8.1/lib/python3.8/site-packages/hatchet/utils/cluBB.py", line 204, in refineClustering
    assert -1 not in set(newassign)
AssertionError

**[setting]**
REF=$REF
LIST="/data/public/dbSNP/b154/GRCh38/GCF_000001405.38.re.vcf.gz"
REF_VERS="hg38"
CHR_NOTATION=true
XDIR=
NORMAL="$Aligned_Path$NORMAL"
BAMS="$Aligned_Path$BAM1 $Aligned_Path$BAM2 $Aligned_Path$BAM3 $Aligned_Path$BAM4"
NAMES="$NAME1 $NAME2 $NAME3 $NAME4"
ALLNAMES="$NORMAL_NAME $NAME1 $NAME2 $NAME3 $NAME4"
J=22
MINREADS=20  
MAXREADS=1000  
BIN="250kb"  #200kb
PHASE="None"

**[script]**
python3 -m hatchet binBAM -N ${NORMAL} -T ${BAMS} -S ${ALLNAMES} -b ${BIN} -g ${REF} -j ${J} -O ${RDR}normal.1bed -o ${RDR}tumor.1bed -t ${RDR}total.tsv |& tee ${RDR}bins.log
python3 -m hatchet SNPCaller -N ${NORMAL} -r ${REF} -j ${J} -c ${MINREADS} -C ${MAXREADS} -R ${LIST} -o ${SNP} |& tee ${BAF}bafs.log
python3 -m hatchet deBAF -st ${SAM} -bt ${BCF} -N ${NORMAL} -T ${BAMS} -S ${ALLNAMES} -r ${REF} -j ${J} -L ${SNP}*.vcf.gz -c ${MINREADS} -C ${MAXREADS} -O ${BAF}normal.1bed -o ${BAF}tumor.1bed |& tee ${BAF}bafs.log
python3 -m hatchet comBBo -c ${RDR}normal.1bed -C ${RDR}tumor.1bed -B ${BAF}tumor.1bed -t ${RDR}total.tsv -p ${PHASE} -e ${RANDOM} > ${BB}bulk.bb
python3 -m hatchet cluBB ${BB}bulk.bb -o ${BBC}bulk.seg -O ${BBC}bulk.bbc -e ${RANDOM} -d 0.1 -tR 0.15 -tB 0.04 \
-u 20 -dR 0.002 -dB 0.002

I tried to solve it myself by looking into the code but I couldn't know what was causing the problem.

Thanks for any advice in advance ,
Jiho

**Comment by simozacca** [comment]
Thanks for your feedback!

@mmyers1 this seems something related to the new clustering, could you please take a look into it and recommend potential tests to perform to fix it?

@jennyp76 Using bootstrapping with `-u` is not required anymore for WES data and I would recommend to first try to run the clustering without. You could use bootstrapping next in case of too high variability of the data or to improve the clustering.

@brian-arnold Could you please update the tutorial to mention this recommendation above for bootstrapping?

**Comment by mmyers1** [comment]
@simozacca I'm not sure what the issue is, as the AssertionError is being thrown by old code (function refineClustering in cluBB.py).

**Comment by simozacca** [comment]
@jennyp76 would you have the possibility to please share with us your `bulk.bb` file that we can use to replicate the erroneous behaviour?

**Comment by jennyp76** [comment]
I uploaded the <bulk.bb.txt> file as you guys have mention.
[bulk.bb.txt](https://github.com/raphael-group/hatchet/files/6272150/bulk.bb.txt)

By the way, what do @mmyers1 mean by the "old code"? Should I have to upgrade something?

**Comment by jennyp76** [comment]
Hi, 

Would it be okay if I get some updates with the error I'm having?
Thank you for helping me solve the problem 
I appreciate for all the effects your team is putting into this amazing tool 

Jiho

**Comment by simozacca** [comment]
> Hi,
> 
> Would it be okay if I get some updates with the error I'm having?
> Thank you for helping me solve the problem.
> I appreciate for all the effects your team is putting into this amazing tool .
> 
> Jiho

It appears that the current implementation of the clustering (which recently changed) is malfunctioning when bootstrapping is used and @mmyers1 is working on a fix for it.

However, our recommendation is to **not** use bootstrapping by default but only in case of substantial clustering errors or substantial underclustering. Thus, could you please try to run without bootstrapping and check whether you can get meaningful results? That is running the following updated command:

```shell
python3 -m hatchet cluBB ${BB}bulk.bb -o ${BBC}bulk.seg -O ${BBC}bulk.bbc -e ${RANDOM} -d 0.1 -tR 0.15 -tB 0.04
```

Also, if you need to better fix the clustering there are two additional parameters that can be used `-K` and `-c`. Please see related documentation.

**Comment by jennyp76** [comment]
Thank you for the rely. 
I followed your recommendation to not use bootstrap for clustering and increased the -tR value to 0.5 since my data is WES and had no problem running it. This is the code I used. However, I got another error while running hatchet solve. I posted the hatchet.log file.
I will attach the **bulk.bbc**  and **bulk.seg** just in case you guys might need it.

Sorry for posting another error rather than a meaningful results :(
Thanks for any advice in advance ,
Jiho

`python3 -m hatchet cluBB ${BB}bulk.bb -o ${BBC}bulk.seg -O ${BBC}bulk.bbc -e ${RANDOM} -d 0.1 -tR 0.5 -tB 0.04`

`python3 -m hatchet solve -i ../${BBC}bulk -n2,6 -p 400 -u 0.06 -eD 6 -eT 12 -g 0.35 -l 0.6 -j ${J} -r ${RANDOM} &> >(tee >(grep -v Progress > hatchet.log))`

 **<hatchet.log> file**
ESC[95mESC[1m# Checking and parsing input arguments
ESC[0mESC[95mESC[1m# Reading and parsing clustered bins in BBC file
ESC[0mESC[95mESC[1m# Reading and parsing bin clusters in SEG file
ESC[0mESC[95mESC[1m# Computing the cluster sizes
ESC[0mESC[95mESC[1m# Filtering clusters based on covered genome size and covered chromosomes
ESC[0mESC[96m# Selected clusters: 2, 8, 28, 48, 30, 27, 26
ESC[0mESC[96m## Features of selected clusters:
ESC[0mESC[96m## 2: SIZE= 22964554.0     #CHRS= 21       (RDR, BAF)= (1.3292289510494144, 0.3438265127667016)-(1.5114092687095069, 0.32354715463502914)-(1.2454379811411083, 0.328759291023442)-(1.2004946095703024, 0.3598262202913366)
## 8: SIZE= 42499998.0  #CHRS= 20       (RDR, BAF)= (0.7921650326563779, 0.44372925103946514)-(0.8093377512646647, 0.39062132068489924)-(0.7613678741777145, 0.3972149070305642)-(0.904498724494066, 0.3280472753113663)
## 28: SIZE= 46750000.0 #CHRS= 20       (RDR, BAF)= (1.0729031376840517, 0.44423180522094574)-(1.35711650478342, 0.369140499065059)-(1.0308211981640314, 0.48416467429985643)-(1.251931556729654, 0.47308501070359876)
## 48: SIZE= 93499998.0 #CHRS= 22       (RDR, BAF)= (0.9764194487632225, 0.5)-(1.1485952903578203, 0.3625485802629657)-(0.9687817134294755, 0.5)-(1.2936077957477317, 0.3667821895396091)
## 30: SIZE= 265959982.0        #CHRS= 21       (RDR, BAF)= (0.9894937301569241, 0.5)-(0.9231254451535484, 0.4813112091263284)-(0.9672370715423475, 0.5)-(0.8645272363989374, 0.3088739031325065)
## 27: SIZE= 778429550.0        #CHRS= 22       (RDR, BAF)= (1.0472029054397494, 0.5)-(1.0654487917925417, 0.5)-(1.020116127899457, 0.5)-(1.0266732170505515, 0.5)
## 26: SIZE= 78500000.0 #CHRS= 22       (RDR, BAF)= (1.0773997152883172, 0.45979172709216865)-(1.1146287503374126, 0.39803090959873383)-(1.0356315751518637, 0.4532602235002686)-(0.9705893328159682, 0.36106090162320814)
ESC[0mESC[95mESC[1m# Finding the neutral diploid/tetraploid cluster
ESC[0mESC[96m## Cluster selected as neutral (diploid/tetraploid) is 27
ESC[0mESC[95mESC[1m# Running diploid
ESC[0mESC[95mESC[1m## Running diploid with 2 clones
ESC[0mTraceback (most recent call last):
  File "/opt/School/python/3.8.1/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/School/python/3.8.1/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/School/python/3.8.1/lib/python3.8/site-packages/hatchet/__main__.py", line 47, in <module>
    solve([solve_bin] + args)
  File "/opt/School/python/3.8.1/lib/python3.8/site-packages/hatchet/bin/HATCHet.py", line 191, in main
    diploidObjs = runningDiploid(neutral=neutral, args=args)
  File "/opt/School/python/3.8.1/lib/python3.8/site-packages/hatchet/bin/HATCHet.py", line 380, in runningDiploid
    results.append((n , execute(args, basecmd, n, outprefix), outprefix))
  File "/opt/School/python/3.8.1/lib/python3.8/site-packages/hatchet/bin/HATCHet.py", line 643, in execute
    raise RuntimeError(error("The following command failed: \n\t\t{}\nwith {}\n".format(cmd, buffer)))
RuntimeError: ESC[91mESC[1mThe following command failed: 
                /opt/School/python/3.8.1/lib/python3.8/site-packages/hatchet/solve ../bbc/bulk -f  -e 6 -j 22 -p 400 -u 0.06 -r 18247 -M 2 -v 2 -c 27:1:1 -n 2 -o ./results.diploid.n2
with ['\x1b[95m\x1b[1m[20:47:54]### Parsing and checking input arguments\t\x1b[0m', '\x1b[92m[20:47:54]## \tInput prefix:  ../bbc/bulk', 'Input SEG:  ../bbc/bulk.seg', 'Input BBC:  ../bbc/bulk.bbc', 'Number of clones:  2', 'Clonal copy numbers:  { 27 [Cluster] : 1|1 [CN] }', 'Help message:  0', 'Maximum number of copy-number states:  -1', 'Maximum integer copy number:  6', 'Number of jobs:  22', 'Number of seeds:  400', 'Minimum tumor-clone threshold:  0.06', 'Maximum resident memory:  -1', 'Time limit:  -1', 'Maximum number of iteratios:  10', 'Random seed:  18247', 'Solving mode:  Coordinate-descent only', 'Verbose:  2', 'Output prefix:  ./results.diploid.n2', 'Diploid threshold:  0.1', 'Base:  1', 'Force amp-del:  1\t\x1b[0m', '\x1b[95m\x1b[1m[20:47:54]### Reading the input SEG file\t\x1b[0m', '\x1b[95m\x1b[1m[20:47:54]### Scale the read-depth ratios into fractional copy numbers using the provided copy numbers\t\x1b[0m', '\x1b[95m\x1b[1m[20:47:54]### Compute allele-specific fractional copy numbers using BAF\t\x1b[0m', '\x1b[95m\x1b[1m[20:47:54]### Starting coordinate descent algorithm on 400 seeds\t\x1b[0m', '\x1b[92m[20:47:55]## Coordinate Descence {\t\x1b[0m', "terminate called after throwing an instance of 'GRBException'", '', '', '', '', '', '']
ESC[0m
ESC[96m## solver:       /opt/School/python/3.8.1/lib/python3.8/site-packages/hatchet/solve
## input:       ../bbc/bulk
## seg: ../bbc/bulk.seg
## bbc: ../bbc/bulk.bbc
## ln:  2
## un:  6
## clonal:      None
## ampdel:      True
## d:   None
## eD:  6
## eT:  12
## ts:  0.008
## tc:  1
## td:  0.01
## tR:  0.08
## tB:  0.04
## mR:  0.08
## mB:  0.04
## limit:       0.6
## g:   0.35
## p:   400
## j:   22
## r:   18247
## s:   None
## m:   None
## u:   0.06
## f:   None
## M:   2
## x:   ./
## diploid:     False
## tetraploid:  False
## v:   2

[bulk.seg.txt](https://github.com/raphael-group/hatchet/files/6303531/bulk.seg.txt)
[bulk.bbc.txt](https://github.com/raphael-group/hatchet/files/6303532/bulk.bbc.txt)

**Comment by simozacca** [comment]
@jennyp76 A `GRBException` indicates an issue with your Gurobi's license. Could you please let us know the following information:
1. What kind of license are you using, either individual or cluster-based?
2. Could you please double check and confirm that your license is still valid and did not expire?
3. Could you please test your license? Please see information at: https://www.gurobi.com/documentation/9.1/quickstart_mac/testing_your_license.html
4. Could you please let us know for which version of Gurobi your license is valid? The bioconda version of HATCHet is compiled with the most recent version of Gurobi and you thus need a license that supports that.

Also, please check this other related open issue https://github.com/raphael-group/hatchet/issues/52#issuecomment-817809897
