### ISSUE TITLE
cluBB: `division by zero` error

### ISSUE THREAD

**Issue by DaGaMs** [raphael-group/hatchet#63]
I'm encountering the following issue with some of our samples:

```
  Traceback (most recent call last):
    File "/opt/gridware/depots/1a8f5697/el7/pkg/apps/python3/3.8.1/gcc-4.8.5/lib/python3.8/runpy.py", line 193, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/opt/gridware/depots/1a8f5697/el7/pkg/apps/python3/3.8.1/gcc-4.8.5/lib/python3.8/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/opt/apps/pkg/apps/hatchet/0.2.11/gcc-4.8.5+python3-3.8.1+gurobi-9.1.2+samtools-1.9+bcftools-1.9/lib/python3.8/site-packages/hatchet/__main__.py", line 45, in <module>
      globals()[command](args)
    File "/opt/apps/pkg/apps/hatchet/0.2.11/gcc-4.8.5+python3-3.8.1+gurobi-9.1.2+samtools-1.9+bcftools-1.9/lib/python3.8/site-packages/hatchet/utils/cluBB.py", line 49, in main
      segments = segmentBins(bb=combo, clusters=clusters, samples=samples)
    File "/opt/apps/pkg/apps/hatchet/0.2.11/gcc-4.8.5+python3-3.8.1+gurobi-9.1.2+samtools-1.9+bcftools-1.9/lib/python3.8/site-packages/hatchet/utils/cluBB.py", line 228, in segmentBins
      return minSegmentBins(sbb, nbins, rd, nsnps, cov, clusters, samples)
    File "/opt/apps/pkg/apps/hatchet/0.2.11/gcc-4.8.5+python3-3.8.1+gurobi-9.1.2+samtools-1.9+bcftools-1.9/lib/python3.8/site-packages/hatchet/utils/cluBB.py", line 234, in minSegmentBins
      mean = {cluster : {sample : float(alpha[cluster][sample]) / float(alpha[cluster][sample]+beta[cluster][sample]) for sample in samples} for cluster in clusters}
    File "/opt/apps/pkg/apps/hatchet/0.2.11/gcc-4.8.5+python3-3.8.1+gurobi-9.1.2+samtools-1.9+bcftools-1.9/lib/python3.8/site-packages/hatchet/utils/cluBB.py", line 234, in <dictcomp>
      mean = {cluster : {sample : float(alpha[cluster][sample]) / float(alpha[cluster][sample]+beta[cluster][sample]) for sample in samples} for cluster in clusters}
    File "/opt/apps/pkg/apps/hatchet/0.2.11/gcc-4.8.5+python3-3.8.1+gurobi-9.1.2+samtools-1.9+bcftools-1.9/lib/python3.8/site-packages/hatchet/utils/cluBB.py", line 234, in <dictcomp>
      mean = {cluster : {sample : float(alpha[cluster][sample]) / float(alpha[cluster][sample]+beta[cluster][sample]) for sample in samples} for cluster in clusters}
  ZeroDivisionError: float division by zero
```

I had a dig around the `bulk.bb` input file, which has a few lines like this one:

```
chr1    2700000 2750000 tumour   1.0423660310815477      1       40.0    0       0       0.5
```

Might this be the problem?

I'm using release version 0.2.11. I haven't tried the 0.3 releases yet - is it likely to be fixed in there?

**Comment by DaGaMs** [comment]
Ah, maybe [this edit](https://github.com/raphael-group/hatchet/commit/1b9cf4b1e31bfcfec7561f3b5a03b031062756cf) might be the fix?

**Comment by vineetbansal** [comment]
Hi @DaGaMs - yes indeed - version `0.3.1` and above of `HATCHet` should fix this issue - you can install from `bioconda` directly, or using the repo code.

**Comment by DaGaMs** [comment]
Indeed fixed, thanks
