### ISSUE TITLE
Specified reference genome does not exist

### ISSUE THREAD

**Issue by prateek-anand** [raphael-group/hatchet#66]
Hi,

I was trying to run hatchet on my laptop, but I kept hitting this error:

    [2021-May-24 19:22:11]# Parsing and checking input arguments
    Traceback (most recent call last):
      File "/usr/local/bin/hatchet", line 33, in <module>
        sys.exit(load_entry_point('hatchet==0.3.1', 'console_scripts', 'hatchet')())
      File "/usr/local/lib/python3.9/site-packages/hatchet/__main__.py", line 63, in main
        globals()[command](args)
      File "/usr/local/lib/python3.9/site-packages/hatchet/utils/run.py", line 44, in main
        count_reads(
      File "/usr/local/lib/python3.9/site-packages/hatchet/utils/count_reads.py", line 16, in main
        args = ap.parse_count_reads_arguments(args)
      File "/usr/local/lib/python3.9/site-packages/hatchet/utils/ArgParsing.py", line 271, in parse_count_reads_arguments
        raise ValueError(sp.error("The specified reference genome does not exist!"))
    ValueError: The specified reference genome does not exist!

I specified the paths for the reference, normal, and tumor bams correctly in hatchet.ini, and they were all in the same directory, but the reference wasn't being passed in for the count_reads function. I looked into run.py and noticed the genome argument was missing:

    count_reads(
                args=[
                    '-N', config.run.normal,
                    '-g', config.run.reference,
                    '-T'

After adding in '-g', config.run.reference, it ran as expected. Was this only a problem on my end?

**Comment by vineetbansal** [comment]
Thanks @prateek-anand  - you're right! This bug escaped our attention due to an errant environment variable which was hiding its effects. I'll fix this pronto and do a `0.3.2` release with this bug fix today.

The `HATCHet` version on `bioconda` should also be fixed by later today, so you might want to keep an eye on when you're able to pull that version in your Dockerfile.

**Comment by prateek-anand** [comment]
Great, thank you for checking in on this!
