### ISSUE TITLE
terminate called after throwing an instance of 'GRBException

### ISSUE THREAD

**Issue by Yu-L** [raphael-group/hatchet#78]
While running the software using the ini profile, I ran into the following problems:

```
Traceback (most recent call last):
  File "/usr/local/bin/hatchet", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/hatchet/__main__.py", line 63, in main
    globals()[command](args)
  File "/usr/local/lib/python3.8/site-packages/hatchet/utils/run.py", line 149, in main
    hatchet_main(args=[
  File "/usr/local/lib/python3.8/site-packages/hatchet/bin/HATCHet.py", line 192, in main
    diploidObjs = runningDiploid(neutral=neutral, args=args)
  File "/usr/local/lib/python3.8/site-packages/hatchet/bin/HATCHet.py", line 381, in runningDiploid
    results.append((n , execute(args, basecmd, n, outprefix), outprefix))
  File "/usr/local/lib/python3.8/site-packages/hatchet/bin/HATCHet.py", line 644, in execute
    raise RuntimeError(error("The following command failed: \n\t\t{}\nwith {}\n".format(cmd, buffer)))
RuntimeError: The following command failed: 
                /usr/local/lib/python3.8/site-packages/hatchet/solve output1/bbc/bulk -f  -e 6 -j 64 -p 400 -u 0.03 -M 2 -v 2 -c 5:1:1 -n 2 -o output1/results/results.diploid.n2
with ['\x1b[95m\x1b[1m[04:46:16]### Parsing and checking input arguments\t\x1b[0m', '\x1b[92m[04:46:16]## \tInput prefix:  output1/bbc/bulk', 'Input SEG:  output1/bbc/bulk.seg', 'Input BBC:  output1/bbc/bulk.bbc', 'Number of clones:  2', 'Clonal copy numbers:  { 5 [Cluster] : 1|1 [CN] }', 'Help message:  0', 'Maximum number of copy-number states:  -1', 'Maximum integer copy number:  6', 'Number of jobs:  64', 'Number of seeds:  400', 'Minimum tumor-clone threshold:  
0.03', 'Maximum resident memory:  -1', 'Time limit:  -1', 'Maximum number of iteratios:  10', 'Random seed:  -1', 'Solving mode:  Coordinate-descent only', 'Verbose:  2', 'Output prefix:  output1/results/results.diploid.n2', 'Diploid threshold:  0.1', 'Base:  1', 'Force amp-del:  1\t\x1b[0m', '\x1b[95m\x1b[1m[04:46:16]### Reading the input SEG file\t\x1b[0m', '\x1b[95m\x1b[1m[04:46:16]### Scale the read-depth ratios into fractional copy numbers using the provided copy numbers\t\x1b[0m', '\x1b[95m\x1b[1m[04:46:16]### Compute allele-specific fractional copy numbers using BAF\t\x1b[0m', '\x1b[95m\x1b[1m[04:46:16]### Starting coordinate descent algorithm on 400 seeds\t\x1b[0m', '\x1b[92m[04:46:16]## Coordinate Descence {\t\x1b[0m', "terminate called after throwing an instance of 'GRBException'", '']
```

The log show that, processing stop at  "Running diploid" step, 
here is my ini profile,
```
[run]
# What individual steps of HATCHet should we run in the pipeline?
# Valid values are True or False
count_reads = True
genotype_snps = True
count_alleles = True
combine_counts = True
cluster_bins = True
plot_bins = True
compute_cn = True
plot_cn = True

# Path to reference genome
# Make sure you have also generated the reference dictionary as /path/to/reference.dict
reference = /data/reference/hg38.fa"
normal = "/data/SAMN05341176/bam/SRR3943943.sorted.marked.bqsr.bam"
bams = "/data/SAMN05341176/bam/SRR3943944.sorted.marked.bqsr.bam"
samples = "SAMN05341176"

# Output path of the run script
output = "output1/"

# How many cores to use for the end-end pipeline?
# This parameter, if specified, will override corresponding 'processes' parameters in individual <step> sections below.
processes = 64

[count_reads]
# Bin size for calculating RDR and BAF
size = 50kb

[genotype_snps]
# Reference version used to select list of known germline SNPs;
# Possible values are "hg19" or "hg38", or leave blank "" if you wish for all positions to be genotyped by bcftools
reference_version = "hg38"
# Does your reference name chromosomes with "chr" prefix?; True or False
chr_notation = True

# Use 8 for WGS with >30x and 20 for WES with ~100x
mincov = 20
# Use 300 for WGS with >30x and Use 1000 for WES with ~100x
maxcov = 1000
# Path to SNP list
#   If blank, HATCHet selects a list of known germline SNPs based on <run.reference_version> and <run.chr_notation>
#   If not, please provide full path to a locally stored list (.vcf.gz) here.
snps = "/bundle/hg38/dbsnp_146.hg38.vcf.gz"

[count_alleles]
# Use 8 for WGS with >30x and 20 for WES with ~100x
mincov = 20
# Use 300 for WGS with >30x and Use 1000 for WES with ~100x
maxcov = 1000

[combine_counts]
# Haplotype block size  used for combining SNPs
blocklength = 50kb
# Path to phased file; leave as "None" to run hatchet without phasing
phase = "None"

[cluster_bins]
diploidbaf = 0.08
tolerancerdr = 0.15
tolerancebaf = 0.04

[plot_bins]
sizethreshold = 0.01
figsize = "6,3"

[compute_cn]
clones = 2,6
seeds = 400
minprop = 0.03
diploidcmax = 6
tetraploidcmax = 12
ghostprop = 0.35
limitinc = 0.6
```

**Comment by simozacca** [comment]
The exception `GRBException` indicates an issue with the required Gurobi license, please refer to these previous issues for guidance: https://github.com/raphael-group/hatchet/issues/16 and https://github.com/raphael-group/hatchet/issues/52

@vineetbansal I guess it might be worth it in the next version to capture such exception and output a better error message?

**Comment by Yu-L** [comment]
yes, its a Gurobi license erro! Thank you for your answer。

**Comment by Yu-L** [comment]
yes, its a Gurobi license erro! Thank you for your answer。
