### ISSUE TITLE
Progressbar Error

### ISSUE THREAD

**Issue by TN-L** [raphael-group/hatchet#86]
Hello,
I am trying to execute hatchet using WES Data. All steps previously to the hatchet step (compute-cn) executed seamlessly.
But while executing compute-cn I get the following error:
ValueError: could not convert string to float: '99,929996'

This error occurs also with other values and with changed data for input.
I have looked at the coordinate_descent.tsv file and I noticed that in this step some values are separated with a ',' as separator. The rest is separated with a '.' .
I included the coordinate_descent file (with a changed ending so I can upload it) and the hatchet.log file. 

[hatchet.log](https://github.com/raphael-group/hatchet/files/6800189/hatchet.log)
[coordinate_descence.txt](https://github.com/raphael-group/hatchet/files/6800198/coordinate_descence.txt)

I am unsure where I can look at to solve this error because only some values are stored in a wrong format.

Thanks for any advice in advance ,
Tim

**Comment by simozacca** [comment]
Could you please let us know what solver are you using?

@vineetbansal : could this be related to the new version with Pyomo?

**Comment by vineetbansal** [comment]
The file `coordinate_descent.tsv` is only generated by the cpp solver (and there has been no change there), so I don't think this is pyomo-related at all. The presence of commas in several columns of this file seems very strange though.

I suspect the problem might be in files generated in the previous step. Would it be possible for you to upload the `*.bbc` and `*.seg` files that are generated as part of the `cluster-bins` step and become the inputs of this `compute-cn` step? That should shed some more light into the problem I think.

**Comment by vineetbansal** [comment]
@TN-L  - if you set the environment variable `HATCHET_COMPUTE_CN_VERBOSITY` to `1` (i.e. only output essential messages), I believe you should be able to proceed, even in the presence of this bug. If that works, then it will give us an idea that this problem is isolated to the objective values as reported by Gurobi. Perhaps the reporting format for Gurobi changed in recent versions..

**Comment by TN-L** [comment]
Here are the files of the `compute-cn` step:
[bulk.bbc.txt](https://github.com/raphael-group/hatchet/files/6807064/bulk.bbc.txt)
[bulk.seg.txt](https://github.com/raphael-group/hatchet/files/6807066/bulk.seg.txt)


After setting the `HATCHET_COMPUTE_CN_VERBOSITY` variable to 1 the `compute-cn` steps runs a bit further but crashes with the following error and files inside the results folder:
`raise RuntimeError(error('Failed to parse the output of the following command because the final objective was not found: \n\t\t{}\n'.format(cmd)))
RuntimeError:1mFailed to parse the output of the following command because the final objective was not found: 
		/home/user/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/solve ../bbc/bulk -f  -e 6 -j 4 -p 400 -u 0.03 -r 6023 -M 2 -v 2 -c 21:1:1 -n 2 -o ./results.diploid.n2
`
[coordinate_descence.txt](https://github.com/raphael-group/hatchet/files/6807074/coordinate_descence.txt)
[hatchet.log](https://github.com/raphael-group/hatchet/files/6807076/hatchet.log)
[results.diploid.n2.bbc.ucn.tsv.txt](https://github.com/raphael-group/hatchet/files/6807077/results.diploid.n2.bbc.ucn.tsv.txt)
[results.diploid.n2.seg.ucn.tsv.txt](https://github.com/raphael-group/hatchet/files/6807078/results.diploid.n2.seg.ucn.tsv.txt)

**Comment by TN-L** [comment]
I tried to rerun the whole pipeline, but without success.
I included the files here as well:
[coordinate_descence.tsv.txt](https://github.com/raphael-group/hatchet/files/6815806/coordinate_descence.tsv.txt)
[hatchet.log](https://github.com/raphael-group/hatchet/files/6815808/hatchet.log)


with set `HATCHET_COMPUTE_CN_VERBOSITY`variable:

[coordinate_descence.tsv.txt](https://github.com/raphael-group/hatchet/files/6815784/coordinate_descence.tsv.txt)
[hatchet.log](https://github.com/raphael-group/hatchet/files/6815785/hatchet.log)
[results.diploid.n2.bbc.ucn.tsv.txt](https://github.com/raphael-group/hatchet/files/6815787/results.diploid.n2.bbc.ucn.tsv.txt)
[results.diploid.n2.seg.ucn.tsv.txt](https://github.com/raphael-group/hatchet/files/6815788/results.diploid.n2.seg.ucn.tsv.txt)

**Comment by vineetbansal** [comment]
Thanks for the files @TN-L - I'll debug this today and get back to you with a fix. Thanks for your patience!

**Comment by vineetbansal** [comment]
@TN-L  - did you install HATCHet from bioconda or did you build it locally using `pip install`? (following something close to the manual instructions for doing this (http://compbio.cs.brown.edu/hatchet/doc_manual_install.html)? If the latter, can I ask you to try to build/install HATCHet by cloning the repo, switching to the `locale-fix` branch, and see if this error goes away?

A few tips if you're willing to test it for us:
  - You can make sure the version of HATCHet you see is v0.4.3 by simply typing in `hatchet` once you've built/installed it.
  - If the fix does work, the file `coordinate_descence.tsv` that is generated as part of the `compute-cn` step should not have any commas in it. If you can verify this, that would be great. This is in fact the root of the problem. It's very weird that some lines of this file have commas while others have a decimal point. I can only assume that certain threads of the `compute-cn` step are landing on a compute node where the locale settings differs from the rest.
  
If manual building is not an option for you, we can look into other ways of testing this out.

**Comment by TN-L** [comment]
I originally installed HATCHet via bioconda, but now i have also installed it manually for the bugfix (with v0.4.3).
The error does not go away with the `locale-fix` branch. But setting my language to `LANG=en_US.UTF-8` fixed the problem for me. Previously it was set to german (de_DE.UTF-8).
To test your conjecture that certain threads are printing out the values with commas, I have run HATCHet with only one thread and it did not crash. I would therefore agree with your assumption, but I do not know how to solve the root of the problem.

Thank you for your help!

**Comment by vineetbansal** [comment]
Great - good to know about your solution. We'll keep this bookmarked in case someone else is having the same problem. Thanks @TN-L. I'll close this issue - feel free to re-open it if it again becomes a problem in the future.

**Comment by janrehker** [comment]
Hi,

German codetable user here as well...
Sorry for commenting on a closed issue and a big thank you for this interesting piece of software!

It appears to me that the error is caused by an exception connected to the data described by @TN-L in combination with line 665-666 in HATCHet.py

`if ';' in nextline:
                progressbar.progress(advance=True, msg="Obj value {}".format(float(nextline.split()[-2][:-1])))`

Occasionaly (and not reproducible, when running the pipeline on the same dataset) the data in the variable 'nextline' happens to contain a comma on systems running with German codetables. Otherwise the content of nextline seems to be OK, besides being malformated.

This can be dealt with either by handleing the exception

`if ';' in nextline:
                try:
                    progressbar.progress(advance=True, msg="Obj value {}".format(float(nextline.split()[-2][:-1])))
                except:
                    progressbar.progress(advance=True, msg="Obj value {}".format(float((nextline.split()[-2][:-1]).replace(",", "."))))`

or just by fixing line 666 by exchanging commas that might occur in the substring by a dot. This will then allow for conversion of the substring into a floating point number

`if ';' in nextline:
                progressbar.progress(advance=True, msg="Obj value {}".format(float((nextline.split()[-2][:-1]).replace(",", "."))))`


While the solution I propose here seem to work for me, I am not sure whether either of them is a valid option due to my lack of understanding of the whole pipeline.


Best regards,
Jan

**Comment by simozacca** [comment]
Thank you for your contribution!

@vineetbansal Since the `replace` is only acting on the numerical part of the string, this might be an acceptable solution? Or maybe we can apply such conversion only when we capture a related exception? What do you think?

**Comment by vineetbansal** [comment]
@simozacca , @janrehker - this looks like an acceptable fix as far as the progress bar is concerned. But I'm afraid the issue goes deeper than this, and any commas generated in the final objective value will cause things to crash down the line (as was happening with the original commenter, traceback below):

```
[0mTraceback (most recent call last):
  File "/home/user/anaconda3/envs/hatchet/bin/hatchet", line 33, in <module>
    sys.exit(load_entry_point('hatchet==0.3.3', 'console_scripts', 'hatchet')())
  File "/home/user/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/__main__.py", line 65, in main
    compute_cn([solve_bin] + args)
  File "/home/user/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/bin/HATCHet.py", line 192, in main
    diploidObjs = runningDiploid(neutral=neutral, args=args)
  File "/home/user/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/bin/HATCHet.py", line 381, in runningDiploid
    results.append((n , execute(args, basecmd, n, outprefix), outprefix))
  File "/home/user/anaconda3/envs/hatchet/lib/python3.8/site-packages/hatchet/bin/HATCHet.py", line 624, in execute
    progressbar.progress(advance=True, msg="Obj value {}".format(float(nextline.split()[-2][:-1])))
ValueError: could not convert string to float: '99,929996'
```

So a 'proper' fix to me seems to be one that should be implemented in the C++ code that generates these values in the first place, not the python-parsing part of it (unless all python code that parses anything out of the stdout/stderr from C++ is modified).

Can I ask you to try the same thing as I asked the original commenter:

...did you install HATCHet from bioconda or did you build it locally using pip install? (following something close to the manual instructions for doing this at http://compbio.cs.brown.edu/hatchet/doc_manual_install.html)? If the latter, can I ask you to try to build/install HATCHet by cloning the repo, switching to the locale-fix branch, and see if this error goes away?

**Comment by janrehker** [comment]
Hi,

Please excuse the delay, my workstation for software testing suffered a major data loss, so I was kind of occupied in getting back into business. ;)

I actually installed through miniconda.
Just tried fighting my way throuch a pip install, but did not succeed.
"ERROR: Could not build wheels for hatchet which use PEP 517 and cannot be installed directly"
This is where I stand regarding technology. Could not build wheels.
Will try again later.


Best regards,
Jan

**Comment by janrehker** [comment]
Seems I am still struggeling..

I am using the python/pip base environment from my conda installation:

pip 21.2.1 from /media/jan/disk1/data/miniconda3/lib/python3.9/site-packages/pip (python 3.9)
(base) jan@jan-KR1014566:/media/jan/disk1/data/programs/hatchet-locale_fix$ python -V
Python 3.9.5

Could switch back to python3.8 from my root installation but this did work for me as well.
Here is the complete output: 


```
(base) jan@jan-KR1014566:/media/jan/disk1/data/programs/hatchet-locale_fix$ pip install .
Processing /media/jan/disk1/data/programs/hatchet-locale_fix
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting scipy
  Using cached scipy-1.7.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (28.5 MB)
Collecting pyomo
  Using cached Pyomo-6.0.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (9.7 MB)
Collecting biopython
  Using cached biopython-1.79-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (2.3 MB)
Collecting pysam
  Using cached pysam-0.16.0.1-cp39-cp39-linux_x86_64.whl
Collecting scikit-learn
  Using cached scikit_learn-0.24.2-cp39-cp39-manylinux2010_x86_64.whl (23.8 MB)
Requirement already satisfied: requests in /media/jan/disk1/data/miniconda3/lib/python3.9/site-packages (from hatchet==0.4.3) (2.25.1)
Collecting psutil
  Using cached psutil-5.8.0-cp39-cp39-manylinux2010_x86_64.whl (293 kB)
Requirement already satisfied: matplotlib in /media/jan/disk1/data/miniconda3/lib/python3.9/site-packages (from hatchet==0.4.3) (3.4.2)
Requirement already satisfied: pandas in /media/jan/disk1/data/miniconda3/lib/python3.9/site-packages (from hatchet==0.4.3) (1.3.1)
Collecting seaborn
  Using cached seaborn-0.11.1-py3-none-any.whl (285 kB)
Requirement already satisfied: numpy in /media/jan/disk1/data/miniconda3/lib/python3.9/site-packages (from biopython->hatchet==0.4.3) (1.21.1)
Requirement already satisfied: pillow>=6.2.0 in /media/jan/disk1/data/miniconda3/lib/python3.9/site-packages (from matplotlib->hatchet==0.4.3) (8.3.1)
Requirement already satisfied: pyparsing>=2.2.1 in /media/jan/disk1/data/miniconda3/lib/python3.9/site-packages (from matplotlib->hatchet==0.4.3) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /media/jan/disk1/data/miniconda3/lib/python3.9/site-packages (from matplotlib->hatchet==0.4.3) (1.3.1)
Requirement already satisfied: python-dateutil>=2.7 in /media/jan/disk1/data/miniconda3/lib/python3.9/site-packages (from matplotlib->hatchet==0.4.3) (2.8.2)
Requirement already satisfied: cycler>=0.10 in /media/jan/disk1/data/miniconda3/lib/python3.9/site-packages (from matplotlib->hatchet==0.4.3) (0.10.0)
Requirement already satisfied: six in /media/jan/disk1/data/miniconda3/lib/python3.9/site-packages (from cycler>=0.10->matplotlib->hatchet==0.4.3) (1.16.0)
Requirement already satisfied: pytz>=2017.3 in /media/jan/disk1/data/miniconda3/lib/python3.9/site-packages (from pandas->hatchet==0.4.3) (2021.1)
Collecting ply
  Using cached ply-3.11-py2.py3-none-any.whl (49 kB)
Requirement already satisfied: idna<3,>=2.5 in /media/jan/disk1/data/miniconda3/lib/python3.9/site-packages (from requests->hatchet==0.4.3) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /media/jan/disk1/data/miniconda3/lib/python3.9/site-packages (from requests->hatchet==0.4.3) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in /media/jan/disk1/data/miniconda3/lib/python3.9/site-packages (from requests->hatchet==0.4.3) (2021.5.30)
Requirement already satisfied: chardet<5,>=3.0.2 in /media/jan/disk1/data/miniconda3/lib/python3.9/site-packages (from requests->hatchet==0.4.3) (4.0.0)
Collecting joblib>=0.11
  Using cached joblib-1.0.1-py3-none-any.whl (303 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-2.2.0-py3-none-any.whl (12 kB)
Building wheels for collected packages: hatchet
Building wheel for hatchet (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /media/jan/disk1/data/miniconda3/bin/python /media/jan/disk1/data/miniconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpbhnf9z2l
       cwd: /tmp/pip-req-build-4u_momu4
  Complete output (79 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/hatchet
  copying src/hatchet/__main__.py -> build/lib.linux-x86_64-3.9/hatchet
  copying src/hatchet/__init__.py -> build/lib.linux-x86_64-3.9/hatchet
  creating build/lib.linux-x86_64-3.9/hatchet/utils
  copying src/hatchet/utils/plot_cn.py -> build/lib.linux-x86_64-3.9/hatchet/utils
  copying src/hatchet/utils/plot_bins.py -> build/lib.linux-x86_64-3.9/hatchet/utils
  copying src/hatchet/utils/TotalCounting.py -> build/lib.linux-x86_64-3.9/hatchet/utils
  copying src/hatchet/utils/__init__.py -> build/lib.linux-x86_64-3.9/hatchet/utils
  copying src/hatchet/utils/cluster_bins.py -> build/lib.linux-x86_64-3.9/hatchet/utils
  copying src/hatchet/utils/CoordinateFinding.py -> build/lib.linux-x86_64-3.9/hatchet/utils
  copying src/hatchet/utils/config.py -> build/lib.linux-x86_64-3.9/hatchet/utils
  copying src/hatchet/utils/combine_counts.py -> build/lib.linux-x86_64-3.9/hatchet/utils
  copying src/hatchet/utils/count_reads.py -> build/lib.linux-x86_64-3.9/hatchet/utils
  copying src/hatchet/utils/Supporting.py -> build/lib.linux-x86_64-3.9/hatchet/utils
  copying src/hatchet/utils/ArgParsing.py -> build/lib.linux-x86_64-3.9/hatchet/utils
  copying src/hatchet/utils/BAMBinning.py -> build/lib.linux-x86_64-3.9/hatchet/utils
  copying src/hatchet/utils/run.py -> build/lib.linux-x86_64-3.9/hatchet/utils
  copying src/hatchet/utils/count_alleles.py -> build/lib.linux-x86_64-3.9/hatchet/utils
  copying src/hatchet/utils/ProgressBar.py -> build/lib.linux-x86_64-3.9/hatchet/utils
  copying src/hatchet/utils/genotype_snps.py -> build/lib.linux-x86_64-3.9/hatchet/utils
  creating build/lib.linux-x86_64-3.9/hatchet/utils/solve
  copying src/hatchet/utils/solve/__init__.py -> build/lib.linux-x86_64-3.9/hatchet/utils/solve
  copying src/hatchet/utils/solve/utils.py -> build/lib.linux-x86_64-3.9/hatchet/utils/solve
  copying src/hatchet/utils/solve/cd.py -> build/lib.linux-x86_64-3.9/hatchet/utils/solve
  copying src/hatchet/utils/solve/ilp_subset.py -> build/lib.linux-x86_64-3.9/hatchet/utils/solve
  creating build/lib.linux-x86_64-3.9/hatchet/bin
  copying src/hatchet/bin/__init__.py -> build/lib.linux-x86_64-3.9/hatchet/bin
  copying src/hatchet/bin/HATCHet-preprocess.py -> build/lib.linux-x86_64-3.9/hatchet/bin
  copying src/hatchet/bin/HATCHet.py -> build/lib.linux-x86_64-3.9/hatchet/bin
  copying src/hatchet/hatchet.ini -> build/lib.linux-x86_64-3.9/hatchet
  running build_ext
  CMake Error: The current CMakeCache.txt directory /tmp/pip-req-build-4u_momu4/CMakeCache.txt is different than the directory /media/jan/disk1/data/programs/hatchet-locale_fix where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
  Traceback (most recent call last):
    File "/media/jan/disk1/data/miniconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/media/jan/disk1/data/miniconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/media/jan/disk1/data/miniconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 248, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-d06v5aad/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 221, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-d06v5aad/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-d06v5aad/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 77, in <module>
      setup(
    File "/tmp/pip-build-env-d06v5aad/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/media/jan/disk1/data/miniconda3/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/media/jan/disk1/data/miniconda3/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/media/jan/disk1/data/miniconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-d06v5aad/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/media/jan/disk1/data/miniconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/media/jan/disk1/data/miniconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/media/jan/disk1/data/miniconda3/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/media/jan/disk1/data/miniconda3/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/media/jan/disk1/data/miniconda3/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 44, in run
      self.build_extension(ext)
    File "setup.py", line 73, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "/media/jan/disk1/data/miniconda3/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-4u_momu4', '-DCMAKE_INSTALL_PREFIX=/tmp/pip-req-build-4u_momu4/build/lib.linux-x86_64-3.9/hatchet', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-4u_momu4/build/lib.linux-x86_64-3.9/hatchet', '-DGUROBI_HOME=', '-DPYTHON_EXECUTABLE=/media/jan/disk1/data/miniconda3/bin/python', '-DCMAKE_BUILD_TYPE=']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for hatchet
Failed to build hatchet
ERROR: Could not build wheels for hatchet which use PEP 517 and cannot be installed directly
```

**Comment by vineetbansal** [comment]
@janrehker - thanks for the info, and thanks for working with us on this issue.

This particular error you're seeing seems to be the result of old `cmake` cache file (`CMakeCache.txt`) somewhere in the current folder. You may want to clone the repository code at the branch and try again, or in any case remove the `dist`, `build` folders (and any `CMakeCache.txt` file that you may have), and try again.

Also note that the environment variable `GUROBI_HOME` should be set to where you downloaded Gurobi `9.0.2` (from https://packages.gurobi.com/9.0/gurobi9.0.2_linux64.tar.gz). In my case, this is `GUROBI_HOME=/data/projects/hatchet/tools/gurobi902/linux64`. I'm seeing build errors with the latest Gurobi (9.1.2), so it's probably best to stick to `9.0.2` using the link above (we'll document this shortly).

Finally, in all my experimentation with Linux, I've found that I also need to set `export CXXFLAGS=-pthread` to build `HATCHet` correctly.

**Comment by janrehker** [comment]
I think, the export `CXXFLAGS=-pthread` did the trick for me, regarding the compiler error. I went back to Gurobi 9.0.2, as well.
That very fact allows me to proudly present a new error message:

`Progress: |█-------------------------------------------------| 3.5% Complete [Obj value 59.365002]Traceback (most recent call last):
  File "/media/jan/disk1/data/miniconda3/envs/hatchet2/bin/hatchet", line 8, in <module>
    sys.exit(main())
  File "/media/jan/disk1/data/miniconda3/envs/hatchet2/lib/python3.8/site-packages/hatchet/__main__.py", line 63, in main
    globals()[command](args)
  File "/media/jan/disk1/data/miniconda3/envs/hatchet2/lib/python3.8/site-packages/hatchet/utils/run.py", line 151, in main
    hatchet_main(
  File "/media/jan/disk1/data/miniconda3/envs/hatchet2/lib/python3.8/site-packages/hatchet/bin/HATCHet.py", line 194, in main
    diploidObjs = runningDiploid(neutral=neutral, args=args)
  File "/media/jan/disk1/data/miniconda3/envs/hatchet2/lib/python3.8/site-packages/hatchet/bin/HATCHet.py", line 385, in runningDiploid
    results.append((n , execute(args, basecmd, n, outprefix), outprefix))
  File "/media/jan/disk1/data/miniconda3/envs/hatchet2/lib/python3.8/site-packages/hatchet/bin/HATCHet.py", line 666, in execute
    progressbar.progress(advance=True, msg="Obj value {}".format(float(nextline.split()[-2][:-1])))
ValueError: could not convert string to float: '59,365002'
(hatchet2) jan@jan-KR1014566:/media/jan/disk1/data/Agilent Exom-2002/hatchet_test$ hatchet
HATCHet v0.4.3`

No issue once again, when switching $LANG to en_US.UTF-8 as suggested by @TN-L. 

Best regards,
Jan.

**Comment by vineetbansal** [comment]
@TN-L , @janrehker  - Can you try giving `HATCHet 0.4.7` (or later) a spin and see if the locale issue is solved?
