### ISSUE TITLE
hatchet/solve Gurobi library not loaded

### ISSUE THREAD

**Issue by kentwait** [raphael-group/hatchet#87]
I encountered the following error running Hatchet on an Intel Mac OS 11.4, Anaconda 4.10.1 running Python 3.9.6

```
Traceback (most recent call last):
  File "/Users/kent/anaconda3/envs/hatchet/bin/hatchet", line 33, in <module>
    sys.exit(load_entry_point('hatchet==0.4.2', 'console_scripts', 'hatchet')())
  File "/Users/kent/anaconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/__main__.py", line 63, in main
    globals()[command](args)
  File "/Users/kent/anaconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/utils/run.py", line 151, in main
    hatchet_main(
  File "/Users/kent/anaconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/bin/HATCHet.py", line 194, in main
    diploidObjs = runningDiploid(neutral=neutral, args=args)
  File "/Users/kent/anaconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/bin/HATCHet.py", line 385, in runningDiploid
    results.append((n , execute(args, basecmd, n, outprefix), outprefix))
  File "/Users/kent/anaconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/bin/HATCHet.py", line 686, in execute
    raise RuntimeError(error("The following command failed: \n\t\t{}\nwith {}\n".format(cmd, buffer)))
RuntimeError: The following command failed:
		/Users/kent/anaconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/solve /Volumes/NVME4TB/projects/ith/data/hatchet/bbc/bulk -f  -e 6 -j 4 -p 400 -u 0.03 -M 2 -v 2 -c 2:1:1 -n 2 -o /Volumes/NVME4TB/projects/ith/data/hatchet/results/results.diploid.n2
with ['dyld: Library not loaded: /Library/gurobi902/mac64/lib/libgurobi90.dylib', 'Referenced from: /Users/kent/anaconda3/envs/hatchet/lib/python3.9/site-packages/hatchet/solve', 'Reason: image not found', '']
```

I installed Hatchet using Anaconda (based on the instructions here: http://compbio.cs.brown.edu/hatchet/README.html#standard-installation) and I downloaded the current version of Gurobi (9.1.2).
ON my Mac, the Gurobi library is installed in `/Library/gurobi912/mac64/lib/libgurobi91.dylib` and not in `/Library/gurobi902/mac64/lib/libgurobi90.dylib` so I think this could be the problem.

Any way to change the path to the Gurobi lib?

Thanks

**Comment by vineetbansal** [comment]
@kentwait - We realize that this is not an ideal solution, but one possible solution here is that you will find the file `libgurobi90.dylib` in the folder `$CONDA_PREFIX/lib` (if you installed `HATCHet` through `bioconda` like you said). If you copy over that file to a folder (that you will have to create) - `/Library/gurobi902/mac64/lib/`, that should allow the `solve` command to proceed. Of course the environment variable `GRB_LICENSE_FILE` needs to be set to a `.lic` file generated after a successful invocation of `grbgetkey`, otherwise you'll see a `GRBException`.

If this works, then we can modify our `HATCHet` bioconda recipe to not insist on the `.dylib` file being present at a particular place. This seems to be an issue only with the Mac version of `HATCHet`, and not the Linux version.
